### ISSUE TITLE
scripts 

### ISSUE THREAD

**Issue by gdimitropoulos** [codesandbox/sandpack#100]
is there a way to add scripts to package json ? 
"scripts": {
    "start": "parcel index.html --open",
    "build": "parcel build index.html"
  },

**Comment by danilowoz** [comment]
Hey, I'd suggest you overwrite the `package.json` file and then there your changes, take a look at this sandbox:
https://codesandbox.io/s/rewrite-package-json-7045x?file=/src/App.tsx

Let me know if it works for you.
