### ISSUE TITLE
Doesn't work with NextJS 13.5.2

### ISSUE THREAD

**Issue by bernaferrari** [codesandbox/sandpack#1006]
# Bug report

## Packages affected

-   [x] sandpack-react

SandpackPreview doesn't work anymore, keeps loading forever. On NextJS 13.4.10 it worked fine.
![image](https://github.com/codesandbox/sandpack/assets/351125/094ede60-43b7-4106-94bc-0e210d72ac7a)

| Software                | Name/Version |
| ----------------------- | ------------ |
| Sandpack-client version | 2.7.1 |
| Sandpack-react version  |  2.7.1 |
| Browser                 | Chrome |
| Operating System        | macOS Ventura |

**Comment by baninaveen** [comment]
Me too facing this issue

**Comment by HUANGXUANKUN** [comment]
yup

**Comment by bernaferrari** [comment]
It is sad sandpack is abandoned

**Comment by danieldelcore** [comment]
You might want to check your network tab to see if any Sandpack requests are being blocked by your next config.

**Comment by danieldelcore** [comment]
Works for me on

- "@codesandbox/sandpack-react": "^2.18.2",
- "next": "14.1.0",

**Comment by namasteaman** [comment]
The same issue has started occurring again after upgrading Next.js to version 14.2.35.
