### ISSUE TITLE
Does the sandpack provider reset on mount of new Sandpack components?

### ISSUE THREAD

**Issue by yaralahruthik** [codesandbox/sandpack#1018]
# Bug report

## Packages affected

-   [ ] sandpack-client
-   [x] sandpack-react

## Description of the problem
I am trying to build an application with multiple tabs. So, each tab is a different sandpack component. One irritating issue is that sandpack loses its status and kind of restarts when I open a different tab.

I might be doing something wrong but here is how my custom button looks like:
```
export default function RunCodeButton() {
  const { sandpack } = useSandpack();

  const handleRunCode = () => {
    if (sandpack.status == 'running') return;

    sandpack.runSandpack();
  };

  return (
    <Button className="rounded-none" onClick={handleRunCode}>
      {sandpack.status !== 'running' ? 'Run Code' : 'Code Running'}
    </Button>
  );
}
```

## What were you doing when the problem occurred?
https://github.com/codesandbox/sandpack/assets/32637966/4edb019e-8414-4386-b791-e71956eb58fe

### What steps can we take to reproduce the problem?
- Separate out the Sandpack components (CodeEditor, Tests, Console) and check the status of sanpack when you mount or remount one of these components.
- Have a custom button to run the sandpack (sandpack.runSandpack).
- Also, my options for sandpack provider are:
```
options={{
        externalResources: data.question.meta.externalCDNs,
        autoReload: true,
        autorun: false, // If true results in infinite loader, problem in NextJS
      }}
```

### Your Environment

| Software                | Name/Version |
| ----------------------- | ------------ |
| Sandpack-client version |      x        |
| Sandpack-react version  |      2.9.0        |
| Browser                 |     Chrome   Version 118.0.5993.70 (Official Build) (arm64)      |
| Operating System        |      MacOS 14.0 (23A344)        |

**Comment by danilowoz** [comment]
Hey, thanks for opening this detailed issue. But could you please provide a sandbox that isolates this problem where we can reproduce it? The first thing that comes to my mind is that the Test tab contains the bundler running, and it should remain running until you leave the application or intentionally unmount it. When you change the tab I guess you unmount the bundler, making it reset to the initial state. Try to simply hide it, instead of unmounting.

**Comment by yaralahruthik** [comment]
@danilowoz If the Tests component contains the bundler then I understand my problem. Thanks!
