### ISSUE TITLE
I've tried again many times, and it still won't display the results.

### ISSUE THREAD

**Issue by IrvingEben** [codesandbox/sandpack#1019]
![image](https://github.com/codesandbox/sandpack/assets/148513311/5fea76f2-b433-4b60-a3f8-39467bd28edd)

**Comment by IrvingEben** [comment]
how to fix this? even I have tried to change the wifi, the result is still like that

**Comment by danilowoz** [comment]
Hey! Could you please create a sandbox to reproduce this error? For example, can you run this same template on the sandpack documentation https://sandpack.codesandbox.io/docs/quickstart?

**Comment by IrvingEben** [comment]
> Hey! Could you please create a sandbox to reproduce this error? For example, can you run this same template on the sandpack documentation https://sandpack.codesandbox.io/docs/quickstart?

I have created an account on sandbox, and after I try to open the link, there I can run the same temeplate on sandpack, and I want to thank you, therefore I can continue this training. sorry if my English is stiff, because my English is not so good.
