### ISSUE TITLE
`<head>` is being replaced inside of React projects

### ISSUE THREAD

**Issue by andrico1234** [codesandbox/sandpack#1049]
# Bug report

## Packages affected

-   [x] sandpack-client
-   [ ] sandpack-react

## Description of the problem

https://www.loom.com/share/18f261cfef6b468ba634265056351faf

In Sandpacks that use a static template, the HTML in the head behaves as expected. If I apply global styles, I can see them reflected in the preview. 

This doesn't seem to be the case with Sandpacks that use a React template. In the Loom, you can see that the styles and the title are being replaced with content that Sandpack injects. 

What's interesting is that this isn'ta problem when I open the project in Codesandbox. 

I also noticed this problem exists in the demo section of the Sandpack homepage.

### What steps can we take to reproduce the problem?

1. [Go to Sandpack Quickstart](https://sandpack.codesandbox.io/docs/quickstart)
2. Choose the React template
3. Choose the File Explorer layout
4. Add global styles to the `index.html`'s head element
5. Observe that the styles don't take effect

### Your Environment

| Software                | Name/Version |
| ----------------------- | ------------ |
| Sandpack-client version |        2.10.0      |
| Sandpack-react version  |     2.10.0         |
| Browser                 |     Arc 1.21.1         |
| Operating System        |    MacOS 13.2           |

I haven't really spent the time to dig into what's causing the problem, but I wanted to know if it was a known limitation, a bug, or something I've done wrong in userland before committing more time to investigate. 

I'll be happy to try and open a PR if this is something that should be fixed. 

Thanks all!

**Comment by danilowoz** [comment]
Hey, thanks for reporting it! Actually, this is a known issue, and we've been exploring alternative ways to address it, but at the moment, we didn't find any way. You can find more details on https://github.com/codesandbox/sandpack/issues/32 if you are interested in reading the history of this issue. 

For now, we recommend importing CSS and JS files instead of adding them to the document head.
