### ISSUE TITLE
I am using sandpack and i am not able to see my code is formatted, so is there any way to achieve this??

### ISSUE THREAD

**Issue by akhilpulikkal** [codesandbox/sandpack#1053]
# Bug report

-   [x] sandpack-react

## I am using sand pack editor and i have to see my code as well formatted 

![image](https://github.com/codesandbox/sandpack/assets/133108102/40d1420f-48b9-4121-b0f5-cef6111ae5ba)

### React 

| Software                | Name/Version |
| ----------------------- | ------------ |
| Sandpack-client version |          |
| Sandpack-react version  |     latest          |
| Browser                 |       chrome       |
| Operating System        |     windows         |

**Comment by akhilpulikkal** [comment]
Anyone can help me please??

**Comment by danilowoz** [comment]
Hey, thanks for opening this issue. Actually, Sandpack doesn't support autoformat or prettier by default, but we provide a way to implement it by yourself. You can check it on the documentation on this page: https://sandpack.codesandbox.io/docs/guides

Hope it helps :)
