### ISSUE TITLE
Support for Image on the top imports

### ISSUE THREAD

**Issue by akhilpulikkal** [codesandbox/sandpack#1067]
# Bug report

## Packages affected

-   sandpack-react

### Your Environment

| Software                | Name/Version |
| ----------------------- | ------------ |
| Sandpack-react version  |    ^2.10.0          |
| Browser                 |        Chrome      |
| Operating System        |      Windows 11        |

**Comment by akhilpulikkal** [comment]
Hey anyone can help me on this?? Please its urgent

**Comment by akhilpulikkal** [comment]
Hey Team, Please help me. i am not able to continue from here, please help me, or please give me any reference??

**Comment by mehmetpekcan** [comment]
Hey @akhilpulikkal. 
Best way to achieve this right now is placing your images into your `public` folder so that you can reference it. Note that, doing so makes that image is also reachable in anywhere under your site.

**Comment by akhilpulikkal** [comment]
> Hey @akhilpulikkal. Best way to achieve this right now is placing your images into your `public` folder so that you can reference it. Note that, doing so makes that image is also reachable in anywhere under your site.

Thanks @mehmetpekcan. it's work for me
