### ISSUE TITLE
Service Worker registration failed (text/html)

### ISSUE THREAD

**Issue by luwes** [codesandbox/sandpack#1068]
# Bug report

## Packages affected

-   [x] sandpack-client
-   [x] sandpack-react

## Description of the problem

console is showing an error since version 2.11.0

> Service Worker registration failed:  DOMException: Failed to register a ServiceWorker for scope ('https://2-11-2-sandpack.codesandbox.io/') with script ('https://2-11-2-sandpack.codesandbox.io/csb-sw.js'): The script has an unsupported MIME type ('text/html').

<img width="1531" alt="SCR-20240125-pokw" src="https://github.com/codesandbox/sandpack/assets/360826/783ccedd-2e41-4122-81a4-68474e8df1e4">

Pinning both the client and react pkg to 2.10.0 fixed the issue on our end.

Used here https://github.com/muxinc/media-chrome/pull/791

Repro here, error visible in the console
https://media-chrome-docs-a1ftyhecw-mux.vercel.app/docs/en/get-started

**Comment by binghuis** [comment]
+1

**Comment by binghuis** [comment]
I've tried several times and have found a temporary solution for now. You can still use the latest version of `@codesandbox/sandpack-react`, but you'll need to additionally configure the package.json file, fixing the version of the `@codesandbox/sandpack-client` package at "2.10.0". I suspect that the issue is caused by the `@codesandbox/sandpack-client` package as it uses an independent version number and doesn't stay in sync with `@codesandbox/sandpack-react`, which depends on it. Therefore, the latest version of `@codesandbox/sandpack-client` directly causes the page to throw an error.

**Comment by binghuis** [comment]
<img width="496" alt="image" src="https://github.com/codesandbox/sandpack/assets/20395726/54d68593-77ba-4591-b1ec-10501bb2511a">

**Comment by binghuis** [comment]
version：2.13.5
<img width="389" alt="image" src="https://github.com/codesandbox/sandpack/assets/20395726/5d0c7e82-ef67-4f64-86dd-645a9e18fd75">

**Comment by hariria** [comment]
Facing this issue (same as @binghuis screenshot) still on `"@codesandbox/sandpack-react": "^2.13.10"`

**Comment by Molnfront** [comment]
Same error for latest version and whatever I do it still try to use: https://2-13-8-sandpack.codesandbox.io/

did not help to use resolutions

**Comment by DUDY206** [comment]
> <img alt="image" width="496" src="https://private-user-images.githubusercontent.com/20395726/305876621-54d68593-77ba-4591-b1ec-10501bb2511a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2NjgxMjksIm5iZiI6MTcxNzY2NzgyOSwicGF0aCI6Ii8yMDM5NTcyNi8zMDU4NzY2MjEtNTRkNjg1OTMtNzdiYS00NTkxLWIxZWMtMTA1MDFiYjI1MTFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDA5NTcwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc5OTdjZTE0MzYxYTgyMmM5NWU4OWYyOGEyZmFkZDk3NjY1MmZlYzc5MGQwMWZjMmUzMWMzYjliYjEzMWI4ZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3cVlO7oZWlP8Sxk5m7LWdfosg6SyJpLIIV5ixJpVKgM">

It's work for me. Many thanks

**Comment by jsartisan** [comment]
It worked for me after i hosted the bundler at a subdomain. My domain is `https://frontend-challenges.com/`
and I hosted the bundler at `https://bundler.frontend-challenges.com`

**Comment by danilowoz** [comment]
It has been fixed in the latest version. Sorry for the long wait!
