### ISSUE TITLE
Option To Rename A File or A Folder

### ISSUE THREAD

**Issue by sharma-sahil-scaler** [codesandbox/sandpack#1083]
# Tell us how you think we can improve Sandpack
Sometime what happen is user wants to rename a particular file so this can handle that use case

## Packages affected

-   [ ] sandpack-client
-   [X] sandpack-react

**Comment by danilowoz** [comment]
I'm closing this issue as it's been a while without any activity, and today Sandpack doesn't support such a feature, and we don't have plans to implement it in the short term. 

Thanks so much!

**Comment by sharma-sahil-scaler** [comment]
👍
