### ISSUE TITLE
Sandpack not working for ReactJS version 18.2.0

### ISSUE THREAD

**Issue by sivaramaaa** [codesandbox/sandpack#1089]
# Bug report

## Packages affected

-   [ ] sandpack-client
-   [x] sandpack-react

## Description of the problem

Sandpack-react is not working with  ReactJS 18.2.0 Both in Firefox and Chrome . 

In Firefox you get this error : 

<img width="1436" alt="Screenshot 2024-02-24 at 10 14 46 AM" src="https://github.com/codesandbox/sandpack/assets/18589720/03b2f9d1-45f0-4667-80e0-cf9e95bbf267">

In Chrome you get a different error : 

Error : "Something went wrong - Cannot read properties of undefined (reading 'join')"

<img width="1436" alt="Screenshot 2024-02-24 at 10 12 18 AM" src="https://github.com/codesandbox/sandpack/assets/18589720/876b5d68-d447-4329-b3e0-41eef7be18a5">

### What steps can we take to reproduce the problem?

```App.js
import { Sandpack } from "@codesandbox/sandpack-react";

export default function App() {
  return (
    <div className="App">
      <h1>Hello CodeSandbox</h1>
      <Sandpack template="react" />;
    </div>
  );
}
```

### Your Environment

| Software                | Name/Version |
| ----------------------- | ------------ |
| Sandpack-client version |       x       |
| Sandpack-react version  |        2.13.1      |
| Browser                 |         Firefox & Chrome     |
| Operating System        |     MacOS         |

**Comment by sivaramaaa** [comment]
There is a similar issue #1088  , but just wanted to provide more steps to reproduces this and also have provided the Codesandbox link : [codesandbox.io/p/sandbox/stoic-mestorf-43ctks](https://codesandbox.io/p/sandbox/stoic-mestorf-43ctks)

**Comment by sivaramaaa** [comment]
Closing as i see it's fixed in : https://github.com/codesandbox/sandpack/pull/1090 .

**Comment by danilowoz** [comment]
Hey! Short answer: I'd use the v2 bundler for simple react templates. 

The bundler was designed to introduce a lighter and faster experience for react.dev. Its low footprint makes it possible to run React sandboxes way faster than the main (v1) bundler, but on the other hand, it can't run everything. Currently, we don't have plans to introduce any missing features in v2, although it's still maintained. That said, we won't sunset any of those solutions either, so it's safe to use any of them. 

It's up to you which solution fits better for you.
