### ISSUE TITLE
Service Worker registration failed: TypeError

### ISSUE THREAD

**Issue by Graquick** [codesandbox/sandpack#1091]
# Bug report

## Packages affected

-   [ ] sandpack-client
-   [x] sandpack-react

## Description of the problem
<img width="768" alt="image" src="https://github.com/codesandbox/sandpack/assets/84386995/fe97f018-7c5c-48ac-8a2d-5348c2236c9d">

## What were you doing when the problem occurred?
Opening the browser with a Sandpack instance in the viewport view causes the error in my console (see screenshot above).

### What steps can we take to reproduce the problem?
I implement two types of sandpack instances in my project: 1. Quickstart Presets, 2. Fully cusomized editor.
Both are implemented by following the official documentation.

### Your Environment

| Software                | Name/Version |
| ----------------------- | ------------ |
| Sandpack-client version |              |
| Sandpack-react version  |^2.12.1|
| Browser                 |Firefox, Chrome, Safari|
| Operating System        |macOS: Sonoma 14.3.1|

**Comment by danilowoz** [comment]
It has been fixed in the latest version. Sorry for the long wait!

**Comment by Graquick** [comment]
Awesome! Thanks!
