### ISSUE TITLE
Prettier code formatting

### ISSUE THREAD

**Issue by Graquick** [codesandbox/sandpack#1092]
# Tell us how you think we can improve Sandpack

## Packages affected

-   [ ] sandpack-client
-   [x] sandpack-react

## What is this feature?
Prettier code formatting.
## How would your idea work?
Code in the active file of an editor would be formatted by Prettier, either 1. on type, or 2. on save. I have this currently configured in my CodeSandbox User settings, and it works perfectly.
## Do you have any examples of how you would like to see us implement it?
I've tried adding `prettier` as a dev dependency, and providing a `settings.json` file in the root, but with no success :(.

Also I had to come up with a workaround for "saving" a file in the editor, as there isn't a builtin function for that. Not sure if this is where my issue stems from 🤷🏾‍♂️:
```typescript
  useEffect(() => {
    const handleKeyDown = (event: KeyboardEvent) => {
      // Check if the key combination is pressed
      if ((event.ctrlKey || event.metaKey) && event.key === 's') {
        // Prevent default behavior (saving the page)
        event.preventDefault();
        // Execute your function to update the current file
        sandpack.updateCurrentFile(
          sandpack.files[sandpack.activeFile].code,
          true
        );
      }
    };

    // Add event listener
    document.addEventListener('keydown', handleKeyDown);

    // Remove event listener when component unmounts
    return () => {
      document.removeEventListener('keydown', handleKeyDown);
    };
  }, [sandpack.files]);
```

**Comment by danilowoz** [comment]
Hey! Just to make sure, have you seen this guide/sandbox where we suggest a possible Prettier implementation?
https://codesandbox.io/p/sandbox/sandpack-prettier-1po91?file=%2Fsrc%2FApp.js%3A23%2C27-23%2C35

Hope it helps

**Comment by Graquick** [comment]
Thanks for the quick reply @danilowoz . I checked the sandbox out, but it seemed to work only when I set my User settings to enable prettier. I don't know how to do these settings with sandpack.

**Comment by Graquick** [comment]
Nevermind, got it to work.

**Comment by faseehahmed1** [comment]
Hey @Graquick 👋, did you get this working with version  `"@codesandbox/sandpack-react": 2.14.4` - I've had no luck. The sandbox above works but `sandpack.updateFile(sandpack.activePath, prettierCode);` `activePath` is no longer a prop in version 2.14.4. 

Any advice is highly valued. :)

**Comment by Graquick** [comment]
Hey @faseehahmed1, YES I did! I'm working with an simple example to give to help you get started. You can expect it to be ready either today, or tomorrow (latest).

**Comment by Graquick** [comment]
Hey @faseehahmed1 once again. As promised here's the sandbox: [Sandpack with Prettier -sandbox](https://codesandbox.io/p/sandbox/sandpack-prettier-forked-6fqpvx?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cly4c8dpg00073p6lssbf5au9%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cly4c8dpg00033p6lyqxep3z0%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cly4c8dpg00043p6l4ehywsel%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cly4c8dpg00063p6lz7juh4e0%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B40%252C60%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cly4c8dpg00033p6lyqxep3z0%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cly4c8dpg00023p6l6fh1lwh1%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A34%252C%2522startColumn%2522%253A39%252C%2522endLineNumber%2522%253A34%252C%2522endColumn%2522%253A39%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522cly4i56oy00023p6jua6sx2to%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A8%252C%2522startColumn%2522%253A43%252C%2522endLineNumber%2522%253A8%252C%2522endColumn%2522%253A43%257D%255D%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522cly4c8dpg00033p6lyqxep3z0%2522%252C%2522activeTabId%2522%253A%2522cly4c8dpg00023p6l6fh1lwh1%2522%257D%252C%2522cly4c8dpg00063p6lz7juh4e0%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cly4c8dpg00053p6lvleptgmz%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522cly4c8dpg00063p6lz7juh4e0%2522%252C%2522activeTabId%2522%253A%2522cly4c8dpg00053p6lvleptgmz%2522%257D%252C%2522cly4c8dpg00043p6l4ehywsel%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cly4c8dpg00043p6l4ehywsel%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Afalse%252C%2522sidebarPanelSize%2522%253A0%257D)

Features
1. Code formatting supports `.js`, `.jsx`, `.ts`, `.tsx`, `.css`, and `.scss` files
2. Embedded prettier logo that shows the current state of the formatted code. If format is successful, logo will appear green for some time. If format causes an error, logo will stay red until formatted correctly.

Notes
1. I've included comments in the sandbox that explain the main functions and hooks
2. I'm debouncing the formatting with `lodash`, and you can easily set the debounce delay in the code. I've set it to 150ms.
3. I explicitely added the newest version to this sandbox, and it worked well with the `sandpack.activeFile` property (see more in the sandbox)

I remember struggling with this, and was so happy when I finally got it working. I really hope this will help you get back to coding fast!
