### ISSUE TITLE
ts-node template

### ISSUE THREAD

**Issue by hariria** [codesandbox/sandpack#1128]
# Tell us how you think we can improve Sandpack

Really love Sandpack. I think for folks who want to have a quick server-side typescript playground, a sandbox template for `ts-node` would be amazing in addition to the vanilla js `node` one. I tried getting around this by instantiating a `node` template and custom `package.json` using `ts-node` in the start script but this didn't work unfortunately

## What is this feature?

`ts-node` sandbox template

**Comment by hariria** [comment]
Would look something like 

```ts
<SandpackProvider
      key="server"
      theme={(theme as "light" | "dark") || "dark"}
      template="ts-node"
```

**Comment by danilowoz** [comment]
Hey, thank you for your suggestion. However, Sandpack currently does not aim to support such a template due to technical limitations and limited internal resources.

Thank you once again for showing your interesting.
