### ISSUE TITLE
Documentation: Hosting the Bundler

### ISSUE THREAD

**Issue by Graquick** [codesandbox/sandpack#1140]
I'm having a hard time self-hosting the bundler. I followed each step of the documentation, but didn't get it to work.

## Where can I get my hosted bundlerURL?

In the documentation,
...

    1. The bundler is part of the codesandbox-client codebase: https://github.com/codesandbox/codesandbox-client
    2. Clone the codesandbox-client and install the dependencies in the root folder (yarn install).
    3. yarn build:deps to build some of the packages lerna needs for internal links.
    create your instance of sandpack with yarn build:sandpack.

This creates a www folder in the root of codesandbox-client. That www folder is the sandpack folder sandpack-client connects to on {version}-sandpack.codesandbox.io. Once you have this hosted on your end you can pass bundlerURL when calling:
...

What does the "Once you have this hosted on your end..." mean?

## How can I host by only cloning the repo?

Do I need to fork the repo first, and then clone my forked version, and finally deploy that version for hosting? I tried this with Vercel, but failed:
<img width="779" alt="image" src="https://github.com/codesandbox/sandpack/assets/84386995/7b25b1d2-05a9-43ba-83a5-58e6c54f1d27">

I'm sorry for so many questions. I'm just so new to all of this.

PS. I have a huge project in the works thanks to Sandpack, and can't wait to share it with all of you!

**Comment by danilowoz** [comment]
Hey!

> What does the "Once you have this hosted on your end..." mean?

Yeah, you need to host it somewhere, like Vercel, Netlify, or any other hosting service, which leads to the next problem.

> "node" is compatible with this module.

Unfortunately, Vercel no longer supports old Node.js versions, and the `codesandbox-client` still relies on Node@16. 


But, let me ask. Do you really need to self-host the bundler in your end? This is not a required step to run Sandpack and you can still rely on CodeSandbox infrastructure in case you can't find any workaround for your issue.

**Comment by Graquick** [comment]
Thanks for the quick reply!

Now, I think I will just rely on the CodeSandbox infrastructure. With the way Sandpack is being developed, if anything did happen (on CodeSandbox end) that affected my project, I trust it would get fixed fast and that I would back it up with something.
