### ISSUE TITLE
add react-vite and react-vite-ts to template definition

### ISSUE THREAD

**Issue by ishan28mkip** [codesandbox/sandpack#1143]
I have used react-vite and react-vite-ts as templates but they are not mentioned in this type maybe we can mention it here to avoid confusion?
https://github.com/codesandbox/sandpack/blob/6361b14265bb197e3758ee0558cd1c03b5ec7a8f/sandpack-client/src/types.ts#L384

**Comment by danilowoz** [comment]
`node` is the environment, while `react-vite` is the preset that contains multiple files
