### ISSUE TITLE
Documentation: Prettier example

### ISSUE THREAD

**Issue by abdrizik** [codesandbox/sandpack#1168]
The Prettier CodeSandbox example provided in the "Guides Overview" section of the documentation is not functioning correctly with the latest updates. When attempting to run the example, it fails to format the code as expected.

Guide: https://sandpack.codesandbox.io/docs/guides/guides-overview
Prettier CodeSandbox: https://codesandbox.io/s/sandpack-prettier-1po91?file=/src/App.js

**Comment by danilowoz** [comment]
Thanks for letting us know! I updated the sandbox, and it's working now
