### ISSUE TITLE
Nextjs-ts

### ISSUE THREAD

**Issue by xKevIsDev** [codesandbox/sandpack#1170]
I wanted to express my appreciation for the Sandpack tool—it’s been incredibly useful. However, I have a small request that I believe would greatly enhance the experience for many users, including myself.

Could you please provide a default template for a Next.js with TypeScript setup? 

Basic Project Structure:
	•	pages/_app.tsx: Custom App component for global styles etc.
	•	pages/index.tsx: A simple home page component.
	•	next.config.js: Basic configuration for Next.js.
	•	tsconfig.json: TypeScript configuration for the project.
	•	public/: Folder for static assets.
	•	styles/: Directory for global CSS files.

**Comment by danilowoz** [comment]
Hey, thank you for your suggestion. However, Sandpack currently does not aim to support the latest Next.js version due to technical limitations and limited internal resources.
