### ISSUE TITLE
Get all code files

### ISSUE THREAD

**Issue by MichaelYuhe** [codesandbox/sandpack#1171]
# Bug report

## Packages affected

- [ ] sandpack-client
- [x] sandpack-react

## Description of the problem

Is there any way to get all code files when using Sandpack? I've specified the template to react-ts and passed some new files, but `sandbox.files` can only get the starter vanilla template code

<img width="310" alt="image" src="https://github.com/user-attachments/assets/da4e6b91-ca44-4043-9d48-735bd68c752b">
<img width="1175" alt="image" src="https://github.com/user-attachments/assets/9652120f-0feb-4d48-81f2-d7b333ae901c">

**Comment by danilowoz** [comment]
Hey, thanks for reporting this issue. Could you please provide a sandbox where I can reproduce this problem?
I tried locally, and I was able to get all the files, including custom changes, so I couldn't find any problem at all. Make sure your console is under the correct SandpackProvider component 

Thanks

**Comment by MichaelYuhe** [comment]
Thanks, I've figured it out, it's my mistake.
