### ISSUE TITLE
Documentation: useSandpackClient

### ISSUE THREAD

**Issue by SOG-web** [codesandbox/sandpack#1176]
can we get a simple docs that cover how to use
useSandpackClient
It registers a new sandpack client and returns its instance, listeners, and dispatch function. Using it when creating a custom component to interact directly with the client is recommended. For other cases, use useSandpack instead.

the docs has not details on how to use it

**Comment by danilowoz** [comment]
Hey! I wish I could spend more time adding details in how to use it, but I can't find more time. 
I just added one example, and I hope it helps you.
