### ISSUE TITLE
Bug: IDs generated during server rendering and hydration do NOT match

### ISSUE THREAD

**Issue by andreifloricel** [codesandbox/sandpack#143]
# Bug report

## Packages affected

- [ ] sandpack-client
- [x] sandpack-react

## Description of the problem

During bundling of larger sandpacks (which have a longer init phase) I get the following warning:
```
Warning: Prop `id` did not match. Server: "enter-instructions-8944" Client: "enter-instructions-1407"
    at p
    at div
    at eval (webpack-internal:///./node_modules/@codesandbox/sandpack-react/dist/esm/index.js:1776:3)
    at div
    at div
    at SandpackStack (webpack-internal:///./node_modules/@codesandbox/sandpack-react/dist/esm/index.js:1482:3)
    at SandpackCodeEditor (webpack-internal:///./node_modules/@codesandbox/sandpack-react/dist/esm/index.js:1977:3)
    at div
    at div
    at SandpackThemeProvider (webpack-internal:///./node_modules/@codesandbox/sandpack-react/dist/esm/index.js:422:49)
    at div
[...]
```

This is reproducible with version 0.2.1 but NOT with version 0.1.16, which makes me suspect that the following patch is the "culprit": https://github.com/codesandbox/sandpack/pull/123/files

Most probably the robust solution would be to use here the new `useId()` to ensure that IDs generated on client & server side match (see https://github.com/reactwg/react-18/discussions/111) 
See also this thread for more details https://github.com/facebook/react/issues/5867

### Your Environment

| Software                | Name/Version |
| ----------------------- | ------------ |
| Sandpack-client version |    0.2.1    |
| Sandpack-react version  |    0.2.1    |

**Comment by danilowoz** [comment]
Note to myself, consider using this React API https://reactjs.org/docs/dom-elements.html#suppresshydrationwarning
