### ISSUE TITLE
Svelte transpiler syntax error

### ISSUE THREAD

**Issue by paolotiu** [codesandbox/sandpack#168]
### Discussed in https://github.com/codesandbox/sandpack/discussions/167

<div type='discussions-op-text'>

<sup>Originally posted by **paolotiu** November 23, 2021</sup>
I tried doing a custom setup following https://codesandbox.io/api/v1/sandboxes/svelte/sandpack, but it doesn't seem to work. How would I go about this? Thank you!

After looking into this more, it seems that any release after v0.1.3 doesn't work with svelte. I'm using this sandbox: https://codesandbox.io/s/sandpack-test-svelte-c1by1?file=/src/App.js.</div>

Here's the error message from the console:
Uncaught SyntaxError: Invalid or unexpected token   svelte-transpiler.279017bb.worker.js:formatted:1

![image](https://user-images.githubusercontent.com/61054234/143026210-321ed65d-0ac2-4f28-9b57-45ef46d52b6b.png)

**Comment by danilowoz** [comment]
It should have been fixed on `v0.7.1`, thanks for letting us know about this problem

**Comment by paolotiu** [comment]
Great! Thanks for the quick fix!
