### ISSUE TITLE
Feature request: feature for view console

### ISSUE THREAD

**Issue by kuduzow** [codesandbox/sandpack#193]
## Tell us how you think we can improve Sandpack

It would be useful to have component like `<SandpackConsole>` that renders... a sandpack's console.

## Packages affected

- [x] sandpack-client (probably) 
- [x] sandpack-react

## How would your idea work?

It might be a component that renders console or props like `<SandpackPreview console>` to include console into preview.

## Do you have any examples of how you would like to see us implement it?

It depends on implementation way. The first example right on codesandbox.io ("Console" button on the bottom of preview).

Another way is something like this:

![localhost_3000_read_html-and-css_tags](https://user-images.githubusercontent.com/2021604/143625823-add38125-ba53-451c-a0b2-195bcf85e1a2.png)

**Comment by danilowoz** [comment]
Hey @kuduzow, that would be great! 

I have added your feature request to our internal backlog which we use to prioritize what to build next. We can't make any promises about the timing, but it's on the list!

If you'd like to work on this feature with us, please create a pull request and we'll help you along the way.

For others landing on this issue, feel free to add more context or simply leave a thumbs up 👍 on this comment if you find this feature useful.

**Comment by rvlewerissa** [comment]
Hi @danilowoz, I was wondering how the following code preview is created (link [here](https://www.patterns.dev/posts/singleton-pattern/)):
<img width="1171" alt="Screen Shot 2022-01-13 at 10 19 59 PM" src="https://user-images.githubusercontent.com/15160023/149357633-0e49f234-4cb4-43dc-a350-e0f75bbf6b37.png">

It looks as if it's using [CodeSandbox Embedding](https://codesandbox.io/docs/embedding), but it doesn't use an iframe. Any idea how to implement something like this? No iframe + console feature.

Thank you!

**Comment by danilowoz** [comment]
Hey @rvlewerissa. The link you sent uses CodeSandbox Embedding, which supports the console component and is wrapped in an iframe. However, we still don't have this component properly working on Sandpack, but we're trying to priority it, as this would be very valuable for the development experience.

We can't make any promise of when we will ship it, but we've been working hard to release it as soon as possible.

**Comment by rvlewerissa** [comment]
@danilowoz Thanks for the really quick response! I just discovered that the example I gave does actually use an iframe, I overlooked 😅

Thanks for the hard work on this feature! Looking forward to it!

**Comment by danilowoz** [comment]
Hey all! I'd like to hear your thoughts about this feature and get to understand what is the best approach for this:
- I'm curious to know what kind of feature the Console component cannot fail?
- Can you provide a great example of what would you consider an excellent console component?
- Are you happy with the current CodeSandbox console component?
- 
Feel free to drop any message here, and 👍 which one you like the most

**Comment by joshwcomeau** [comment]
Hi @danilowoz!

Overall, I'm pretty happy with the CodeSandbox console. I like that it has a clear button, just like the browser console.

For Sandpack, I'm hoping that there will be a standalone component (`SandpackConsole`) so that I can build my own layouts with it. I'm less interested in a tab for the console. I'll either want to always show the console, or never show it.

My usecase: occasionally, my sandpacks will be demonstrating console output rather than a live preview. Sometimes, I want to show a particular dev warning. In other cases, I have little JS-based exercises, and the goal is for the user to edit the code and then check the console to see the logged output (rather than checking the preview pane to see the UI).

It might also be good to include timestamps? It can be useful to know when an item was logged. Or, alternatively, maybe the console could be automatically cleared when the code re-runs?

**Comment by JoeShep** [comment]
I am building a code-teaching tool, so starting off with easy examples of JS functions that simply log to the console is important. I plan to write some testing functions that verify the logged output is correct, in order to provide instant feedback to the student. I've already found your example of capturing console.log data with `if (msg.type === "console" && msg.codesandbox)` @danilowoz, so thanks for that! But, being able to easily display the console for the student would be just what I need.

**Comment by nimeshnayaju** [comment]
It'd be great if the `console` logs came with the associated line numbers and file names. I've attached a screenshot of Chrome console logs that show the console log along with file name and line numbers.

<img width="499" alt="Screen Shot 2022-07-15 at 5 06 49 PM" src="https://user-images.githubusercontent.com/35807215/179326142-dbe706c9-e7b2-4bd3-837d-09daffd85e91.png">

**Comment by hussamkhatib** [comment]
Hey @danilowoz , 
I might be able to work on this.
Can you point me to right direction so that I can explore a bit and decide If I can do it or not.

**Comment by danilowoz** [comment]
Hey @hussamkhatib, thanks. But currently, it's working in progress on https://github.com/codesandbox/sandpack/pull/546

There are still a few challenging there, but hopefully I'll be able to ship it on the upcoming weeks

**Comment by danilowoz** [comment]
Hey all! I'm excited to share that we have a beta version of `SandpackConsole` 🎉 

I made a light version of a console, meaning that it will not support all console types or some very specific cases. The idea is to keep Sandpack light and modular; for any other advanced case, I'd recommend going for [console-feed](https://github.com/samdenty/console-feed). 

Plus, I would really appreciate it if we could exhaustively test this new component and report any eventual problems in this issue. Here's the [sandbox](https://codesandbox.io/s/sandpackconsole-7q48py?file=/package.json)! 

![localhost_6006_iframe html_id=components-console--preset args= viewMode=story](https://user-images.githubusercontent.com/4838076/185651783-8bed3e21-0c95-4788-a043-4552164a82af.png)

Documentation is coming next! But, here's a summary:
- New hook: `useSandpackConsole`;
- New component: `SandpackConsole`;
- New option: `<Sandpack options={{ showConsole: true }} />`;

**Comment by iampava** [comment]
First of all thanks a lot for this feature! It's exactly what I was looking for 🙌

I got a small question: is it currently possible to clear the console between renders?

**Comment by danilowoz** [comment]
Hey, thanks! 

I don't think it's possible now, but if you wish this feature, please create another issue, and then we can address it. It must be something [around here](https://github.com/codesandbox/sandpack/blob/main/sandpack-react/src/components/Console/useSandpackConsole.ts#L30): when it gets a message from a refresh or similar, then clean the logs.

**Comment by iampava** [comment]
@danilowoz thanks. Added a feature idea: https://github.com/codesandbox/sandpack/issues/692
