### ISSUE TITLE
Additional Templates

### ISSUE THREAD

**Issue by alexnm** [codesandbox/sandpack#2]
Currently on react, vue and vanilla are added in the library. Ideally, we should support a wide range of templates. 
- [ ] preact
- [ ] angular
- [ ] svelte
- [ ] react-typescript
- [ ] static (no bundling at all?)

The long term feature would be to dynamically fetch template data from codesandbox and avoid hardcoding the files and dependencies.

**Comment by nkovacic** [comment]
Typescript templates are much needed, they are becoming increasingly popular. A great feature would also be loading user-defined templates or even loading them from a Github repository.

**Comment by alexnm** [comment]
closing this as we want to integrate the template fetching as soon as possible
