### ISSUE TITLE
Self hosting the bundler

### ISSUE THREAD

**Issue by vipulbhj** [codesandbox/sandpack#23]
Here the documentation mentions that we can self host the bundler, 
> I want to highlight that you can also host the bundler by yourself, all necessary files are in the sandpack folder.

It mentions the `sandpack` folder, which I am confused about slightly as to which folder are we talking about here and also, how would I go about it If I wanted to self host the bundler. If I understand correctly, Sandpack imports currently point to `...${version}_codesandbox.io...` and I haven't found any option to change this to some other url. 

Can you explain the process of self hosting bundler a little more please.

**Comment by alexnm** [comment]
Yes. I will try to document this in the `sandpack-client` readme.

- the bundler is part of the codesandbox-client codebase: https://github.com/codesandbox/codesandbox-client
- you can create your instance after you install dependencies with `yarn` if you run `yarn build:sandpack` 
- this creates a `www` folder in the root folder (I know, not the best naming)
- that `www` folder is the `sandpack` folder that `sandpack-client` connects to on `{version}-sandpack.codesandbox.io`
- once you have this hosted on your end, you can pass `bundlerURL` when calling `new SandpackClient(iframe, sandboxInfo, { bundlerURL: 'https://your-hosted-version' } )`
- or, if you use `sandpack-react`, you can bundlerURL in the options of the `Sandpack` preset

**Comment by vipulbhj** [comment]
Hey @alexnm 

Thank you so much for all your help :)

**Comment by alexnm** [comment]
Sure, anytime.

If the steps work for you, feel free to submit a PR to the readme of `sandpack-client`, with a section after the `Why is the bundler hosted externally`. every contribution is much appreciated at this point, since we just started testing this project. 

And also, let us know what you build with it, we'd love to showcase some of the community projects around sandpack

**Comment by vipulbhj** [comment]
Sounds good, I will keep you in the loop as to how our experiments go :)

**Comment by vipulbhj** [comment]
Hey @alexnm ,  I am getting this error while running the build command as you had mentioned.

```javascript
➜ yarn build:sandpack

yarn run v1.22.10
$ lerna run build:sandpack-sandbox --scope app --stream
lerna notice cli v3.16.4
lerna info versioning independent
lerna info filter [ 'app' ]
lerna info Executing command in 1 package: "npm run build:sandpack-sandbox"
app: > app@0.1.1 build:sandpack-sandbox /Users/vipulbardwaj/Work/POCs/codesandbox-client/packages/app
app: > cross-env NODE_ENV=production SANDPACK=true SANDBOX_ONLY=true node scripts/build.js && cross-env SANDBOX_ONLY=true yarn copy-assets
app: internal/modules/cjs/loader.js:638
app:     throw err;
app:     ^
app: Error: Cannot find module '@codesandbox/common/lib/version'
app:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
app:     at Function.Module._load (internal/modules/cjs/loader.js:562:25)
app:     at Module.require (internal/modules/cjs/loader.js:692:17)
app:     at require (internal/modules/cjs/helpers.js:25:18)
app:     at Object.<anonymous> (/Users/vipulbardwaj/Work/POCs/codesandbox-client/packages/app/config/webpack.prod.js:13:17)
app:     at Module._compile (internal/modules/cjs/loader.js:778:30)
app:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
app:     at Module.load (internal/modules/cjs/loader.js:653:32)
app:     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
app:     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
app:     at Module.require (internal/modules/cjs/loader.js:692:17)
app:     at require (internal/modules/cjs/helpers.js:25:18)
app:     at Object.<anonymous> (/Users/vipulbardwaj/Work/POCs/codesandbox-client/packages/app/scripts/build.js:10:16)
app:     at Module._compile (internal/modules/cjs/loader.js:778:30)
app:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
app:     at Module.load (internal/modules/cjs/loader.js:653:32)
app: npm ERR! code ELIFECYCLE
app: npm ERR! errno 1
app: npm ERR! app@0.1.1 build:sandpack-sandbox: `cross-env NODE_ENV=production SANDPACK=true SANDBOX_ONLY=true node scripts/build.js && cross-env SANDBOX_ONLY=true yarn copy-assets`
app: npm ERR! Exit status 1
app: npm ERR!
app: npm ERR! Failed at the app@0.1.1 build:sandpack-sandbox script.
app: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
app: npm ERR! A complete log of this run can be found in:
app: npm ERR!     /Users/vipulbardwaj/.npm/_logs/2021-03-16T07_42_43_406Z-debug.log
lerna ERR! npm run build:sandpack-sandbox exited 1 in 'app'
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by alexnm** [comment]
right, missed one thing, first time you setup the codebase you need after `yarn` a `yarn:build:deps`, this builds some of the packages in the monorepo so lerna can use the dist folders to link them. will update the initial comment as well
