### ISSUE TITLE
Bug: sandpack-react: Duplicate entry points

### ISSUE THREAD

**Issue by apostololeg** [codesandbox/sandpack#250]
_FIrst of all - thank you for nice tool! I'm really happy to use it in my projects :raised_hands:_ 

# Bug report

1) This setup gives 2 tabs with same title `App.tsx`, and renders default template in preview, instead of my `App.tsx`
```js
<Sandpack
  template="react-ts"
  files={{
    "/App.tsx": code
  }}
/>
```

2) This setup gives no tabs, but nothing renders in preview
```js
<Sandpack
  template="react-ts"
  files={{
    "/App.tsx": code
  }}
  customSetup={{ entry: "/App.tsx", main: "/App.tsx" }}
/>
```

Expected: 
- no tabs
- preview renders my provided example

You can try it in sandbox https://codesandbox.io/s/sandpack-codesandbox-rendering-conflict-forked-hfuip

**Comment by uyarn** [comment]
Hi,@apostololeg, try to add`src/` prefix befor 'App.tsx' to cover the App.tsx file.
since the template of react-typescript has a `src` root.
you can try my forked codesanbox https://codesandbox.io/s/sandpack-codesandbox-rendering-conflict-forked-rq37q?file=/src/App.js

**Comment by uyarn** [comment]
@danilowoz, the template of `react` and `react-typescript` is different,  which is confusing sometimes.
I think it's better to unify the format of this 2 react templates.

**Comment by apostololeg** [comment]
@uyarn thank you for response, but adding `src/` did not fix that nothing renders in the preview area.
There just empty root `<div id="root"></div>`
Any ideas why it happen?

**Comment by uyarn** [comment]
@apostololeg , you need a `index.tsx` as well if you need a custom setup, you can view the source code
![image](https://user-images.githubusercontent.com/26377630/146170105-34fd773a-1423-4ef0-9c85-e0800668b82f.png)

**Comment by uyarn** [comment]
try the new demo https://codesandbox.io/s/sandpack-codesandbox-rendering-conflict-forked-hf5rm?file=/src/App.js

**Comment by apostololeg** [comment]
> you need a index.tsx as well if you need a custom setup, you can view the source code

Why? Looks like the `customSetup.entry` here to change the default entry point `index.tsx` to some custom (`App.tsx` for example). Isn't it?
https://sandpack.codesandbox.io/docs/api/react/interfaces/SandpackSetup#entry
Btw, would be great when you add some description to this fields in the documentation, to clarify the usage. 🙏 

> try the new demo https://codesandbox.io/s/sandpack-codesandbox-rendering-conflict-forked-hf5rm?file=/src/App.js

Sorry, but this demo not working too, because there are rendered "Hello world" instead of `<div>1</div>`

**Comment by danilowoz** [comment]
It has been addressed on https://github.com/codesandbox/sandpack/pull/268, please let me know if I covered all topics/problems mentioned here.

Thanks for raising up this issue.
