### ISSUE TITLE
Feature request: Add NextJS, NextJS TS templates

### ISSUE THREAD

**Issue by AnishDe12020** [codesandbox/sandpack#254]
# Tell us how you think we can improve Sandpack

## Packages affected

- [ ] sandpack-client
- [x] sandpack-react

## What is this feature?
NextJS, NextJS typescript templates can be added to the library

## How would your idea work?
NextJS, NextJS TS templates will be available to the user to use

## Do you have any examples of how you would like to see us implement it?
It would work just like the other pre-built templates do

**Comment by danilowoz** [comment]
Hey! Just answered it here https://github.com/codesandbox/sandpack/discussions/253
