### ISSUE TITLE
Bug: Same code in sandpack need dynamic fetch npm file, and in codesandbox.io don't need

### ISSUE THREAD

**Issue by mcuking** [codesandbox/sandpack#265]
# Bug report

## Packages affected

- [x] sandpack-client
- [x] sandpack-react

## Description of the problem

I write react code which use [antd npm](https://www.npmjs.com/package/antd) in the codesandbox, and codesandbox will preload antd npm source code https://prod-packager-packages.codesandbox.io/v2/packages/antd/4.17.3.json. In the compilation of react code, it don't need to dynamic fetch antd-required npm file. Link to sandbox: 

https://codesandbox.io/s/vigilant-forest-h4x0l

But the same code in the sandpack, it will  dynamic fetch many antd-required npm file in the compilation,  although all the files is in the preload npm https://prod-packager-packages.codesandbox.io/v2/packages/antd/4.17.3.json. It makes the compilation time too long. Link to sandbox: 

https://codesandbox.io/s/festive-brown-7nd8h

The bundler code which [Codesandbox](https://codesandbox.io/) and [Sandpack](https://github.com/codesandbox/sandpack) uses  should be the same（https://github.com/codesandbox/codesandbox-client/tree/master/packages/sandpack-core）, why there are different behaviors?

![image](https://user-images.githubusercontent.com/22924912/146504227-3d395e29-2d69-4d47-b670-5ca3ae0cd850.png)

### What steps can we take to reproduce the problem?

https://codesandbox.io/s/vigilant-forest-h4x0l

![image](https://user-images.githubusercontent.com/22924912/146480325-6ee13a75-4fc8-4fa9-8b72-791ed225da78.png)

https://codesandbox.io/s/festive-brown-7nd8h

![image](https://user-images.githubusercontent.com/22924912/146480486-063e3b0d-47ed-46ba-a323-639569b34526.png)

### Your Environment

| Software                | Name/Version |
| ----------------------- | ------------ |
| Sandpack-client version |      v0.10.6       |
| Sandpack-react version  |      v0.10.6       |
| Browser          |      Chrome/96.0.4664.110        |
| Operating System |        MacOS/11.5.2      |

**Comment by danilowoz** [comment]
Hey, @CompuIves @DeMoorJasper might you guys help with this issue?

**Comment by danilowoz** [comment]
Solved on https://github.com/codesandbox/codesandbox-client/issues/6359
