### ISSUE TITLE
Feature request: Allow loading pre-transpiled code/html into preview iframe, bypassing compilation

### ISSUE THREAD

**Issue by christian-schulze** [codesandbox/sandpack#271]
# Tell us how you think we can improve Sandpack

## Packages affected

- [X] sandpack-client
- [X] sandpack-react

## What is this feature?
After editing js/html content in the editor, and seeing the compiled result in the preview iframe, have the ability to export the compiled js and html (for saving in a database), then allow loading that pre-compiled content back into the iframe at a later time.

The intention here is for a kind of production mode with no editor available, optimised for speed.

## How would your idea work?
We can access the compiled code by listening for messages of type `state`. The compiled code and related data being available under `state.transpiledModules`.
We then need a way to feed that info back into the iframe for rendering, bypassing any compilation. Maybe the `SandpackClient` class could be extended to support this, something like this:
```js
const client = new SandpackClient(
  iframeRef.current,
  { files, transpiledModules },
  { loadTranspiledModules: true }
);
```
The `files` object is required to access `/index.html`, `transpiledModules` comes directly from the `state` message, and then passing the `loadTranspiledModules` boolean option to enable loading the transpiled modules and bypass any compilation.

I'm not entirely sure how the iframe would inject the transpiled code and html, but I believe we could extract parts of the `compile` function here maybe?
https://github.com/codesandbox/codesandbox-client/blob/master/packages/app/src/sandbox/compile.ts#L464 

Open to ideas on how this could work. Also, I would love to know if there is a way we could do this now, even if it means posting a message to the iframe and running custom code to do the injecting.

## Do you have any examples of how you would like to see us implement it?

**Comment by danilowoz** [comment]
Hey @christian-schulze, thanks for raising this issue.
It's very interesting that you mentioned this problem because we have been working internally on a refactor to optimize the transpile step in the bundler, plus caching its output for other sandboxes. We still don't know when we'll be able to implement it, but it seems very promising so far. 

@DeMoorJasper is out for the holidays, but let me know if I'm assuming anything wrong here.

**Comment by christian-schulze** [comment]
Hi @danilowoz, thanks for responding so soon!

> optimize the transpile step in the bundler, plus caching its output for other sandboxes.

This sounds like it will cover what I'm asking for :+1:

A further question regarding the cache...Will it have an API to allow reading/writing its contents? This will enable saving bundled output to a database for later reloading.

**Comment by danilowoz** [comment]
Moved the discussion to https://github.com/codesandbox/sandpack/issues/295
