### ISSUE TITLE
Better API to update files

### ISSUE THREAD

**Issue by zehfernandes** [codesandbox/sandpack#28]
I don't know if this is the best option, but I think it confuses the need to change the active file to update a specif file's code.

```react
changeActiveFile(file);
updateCurrentFile(code);
```

Maybe we can have a global Function to update it:

```react
const { sandpack } = useSandpack();
const { files, updateFileCode } = sandpack;

updateFileCode(code, files[1]) 
```

**Comment by alexnm** [comment]
I'm thinking to keep two functions on the context `sandpack` object:

```
  updateFile: (path: string, newCode: string) => void;
  updateCurrentFile: (newCode: string) => void;
```
