### ISSUE TITLE
Bug: Nothing renders in preview

### ISSUE THREAD

**Issue by apostololeg** [codesandbox/sandpack#281]
from https://github.com/codesandbox/sandpack/issues/250

# Bug report

## Packages affected

- [ ] sandpack-client
- [x] sandpack-react

## Description 

With this configuration:
```jsx
const code = `
export default function App() {
  return '12312312';
};
`;

<Sandpack
  template="react-ts"
  files={{
    "/App.tsx": code
  }}
  customSetup={{ entry: "/App.tsx", main: "/App.tsx" }}
/>
```

**Actual:** Nothing renders. Empty `<div id="root"></div>`
**Expected:** Render `<div id="root">12312312</div>`

Try it in sandbox https://codesandbox.io/s/sandpack-codesandbox-rendering-conflict-forked-hn9i1

**Comment by danilowoz** [comment]
Hey @apostololeg 
The entry point of the template needs to remain the `index.tsx`, as this file is in charge of rendering the application:

```jsx
const code = `export default function App() {
  return '12312312';
};
`;

export default function App() {
  return (
    <Sandpack
      template="react-ts"
      files={{
        "/App.tsx": code
      }}
      customSetup={{ entry: "/index.tsx", main: "/App.tsx" }}
      options={{ showTabs: true, openPaths: ["/index.tsx"] }}
    />
  );
}
```

Here's an example: https://codesandbox.io/s/sandpack-codesandbox-rendering-conflict-forked-i7lwb?file=/src/App.js

Hope it solves your problem

**Comment by apostololeg** [comment]
Thanks a lot ❤️ 
[Now it's working properly](https://codesandbox.io/s/sandpack-codesandbox-rendering-conflict-forked-xw9b5?file=/src/App.tsx:328-348).
