### ISSUE TITLE
Feature request: export the icons

### ISSUE THREAD

**Issue by smeijer** [codesandbox/sandpack#287]
It would be great if the used icons, like `RefreshIcon` and `CSBIcon` were "exported" as well. That way it's a tiny bit easier to customize certain buttons. For example, to modify the refresh button to add a label to it:

```jsx
<button>
  <RefreshIcon /> refresh
</button>
```

or:

```jsx
<button>
  <CSBIcon /> open in CodeSandbox
</button>
```

**Comment by danilowoz** [comment]
Yeah, I think we can do it. I can't see why not.
