### ISSUE TITLE
Multiple Previews in the same provider

### ISSUE THREAD

**Issue by zehfernandes** [codesandbox/sandpack#29]
Allow multiple previews in the same provider. Very powerful if combined with some preview props like viewport or routes.

**Comment by nkovacic** [comment]
Also stumbled into the same issue. Would be great if the Preview would support adding starting URL so that each preview could potentially show different routes/pages.

**Comment by nkovacic** [comment]
Looks like it is in the works https://github.com/codesandbox/sandpack/tree/exp/multiple-previews

**Comment by alexnm** [comment]
Yes, I've been experimenting with this, but it's a bit on hold while I work on some other things. Unfortunately the original requirements of sandpack were assuming 1 bundler 1 preview for each sandpack instance, hence the architecture needs a bit of an overhaul to make this work, especially if you want to have a dynamic number of previews at runtime
