### ISSUE TITLE
Feature request: Guidelines for performance improvements

### ISSUE THREAD

**Issue by andreifloricel** [codesandbox/sandpack#292]
At the moment, there is a significant performance difference between sandpack-bundler and codesandbox.
Take codesandbox as an example: https://codesandbox.io/s/stoic-nova-iv89h

1. In codesandbox, the initial load takes quite some time, but any subsequent refresh takes very little time, which leads me to believe that there is some caching in the background
2. When I embed the exact same project with Sandpack, the initial load **takes longer than in Codesandbox** and there are **no improvements on subsequent changes/refreshes**

It is possible to provide some:
1. general guidelines for performat Codesandboxes? In my example, I suspect that transpilation is the main culprit for the long initial load. 
How should I structure my projects to avoid "performance drains" & benefit from all the Codesandbox performance tweaks which happen in the background?
2. suggestions for getting "snappier" projects embedded with Sandpack (at least on par with Codesandbox performance)?

**Comment by DeMoorJasper** [comment]
Hey, we use the exact same bundler in codesandbox as is published with the sandpack package, so actual bundling/transformation speed should be identical.

However on codesandbox we have a server side redis cache which makes initial loads almost instant as it does not need to transpile anything initially.

We have some things planned to make this better for all sandpack users (a cache that isn't tied to a sandbox and some other improvements), hopefully we can release them soon.

**Comment by danilowoz** [comment]
Moved the discussion to https://github.com/codesandbox/sandpack/issues/295
