### ISSUE TITLE
Feature request: performance improvements

### ISSUE THREAD

**Issue by danilowoz** [codesandbox/sandpack#295]
This issue aims to centralize all concerns related to performance and what actions Sandpack is taking to solve them.

**How to skip the transpiled step? Or how to load pre-transpiled code?**
We have already addressed an internal solution for it, which aims to cache all compiled files and share them between sandboxes with the same dependencies.

**Why codesandbox.io loads faster than Sandpack?**
We use the exact same bundler in codesandbox as is published with the sandpack package, so actual bundling/transformation speed should be identical. However, on CodeSandbox we have a server-side redis cache which makes initial loads almost instant as it does not need to transpile anything initially. Again, we have some things planned to make this better for all sandpack users (a cache that isn't tied to a sandbox and some other improvements).

Related https://github.com/codesandbox/sandpack/issues/292, https://github.com/codesandbox/sandpack/issues/271, https://github.com/codesandbox/sandpack/discussions/259

**Comment by christian-schulze** [comment]
This is sounding really promising!

In the meantime, I've hacked together a working solution for loading pre-transpiled code here:
https://github.com/christian-schulze/codesandbox-client/commit/c5330188ae4477961339490cc94416ab7bef716a

Looking forward to making use of the official feature when its ready :gift:

**Comment by joshwcomeau** [comment]
I'm thrilled to hear you're working on this 💯

In my own usecase, I have a "fullscreen" button that transfers to a new Sandpack in a Portal. Right now, there's a really noticeable transpile step as the component has to start from scratch:

https://user-images.githubusercontent.com/6692932/150875286-46f3abe5-dff1-42ed-94d8-53e549afc194.mp4

If I only have to pay that transpile cost when the page first loads, it would _greatly_ improve the user experience.

Thanks so much for your work on this project!

**Comment by PeterDraex** [comment]
@danilowoz Could you provide a time frame when the cache feature could be released? Are we talking weeks or months?

**Comment by PeterDraex** [comment]
@danilowoz Will TypeScript be supported?

**Comment by PeterDraex** [comment]
Is this already available in #375?

**Comment by danilowoz** [comment]
ok, let's make it official, please read https://github.com/codesandbox/sandpack/discussions/416

😄

**Comment by danilowoz** [comment]
@joshwcomeau I'm curious to know if you gave the new bundler a try. We made some significant improvements and progress toward removing dependencies and transpile overhead. Feel free to direct me on Twitter or discord to discuss more about it, I'm looking forward to understanding how we can help you.
