### ISSUE TITLE
Feature request: Support read-only mode for CodeEditor

### ISSUE THREAD

**Issue by andreifloricel** [codesandbox/sandpack#296]
# Tell us how you think we can improve Sandpack

In some cases it would be useful to control the editability of the code editor.
As of now (0.12.0), we can use either a [CodeEditor](https://sandpack.codesandbox.io/docs/advanced-usage/components#code-editor) or a [CodeViewer](https://sandpack.codesandbox.io/docs/advanced-usage/components#code-viewer).  

Feature request #97 is somewhat related to this (file-based editability), but this feature is easier to implement because the underlying CodeMirror already supports a "ReadOnly" property.

## Packages affected

- [ ] sandpack-client
- [x] sandpack-react

## How would your idea work?

Add a new `readOnly` [CodeEditor prop](https://github.com/codesandbox/sandpack/blob/v0.12.0/sandpack-react/src/components/CodeEditor/index.tsx#L17) (default: `false`) which is then passed to the underlying CodeMirror which [already supports](https://github.com/codesandbox/sandpack/blob/v0.12.0/sandpack-react/src/components/CodeEditor/CodeMirror.tsx#L69) this property.

When/If #97 is implemened, it would just mean that the editability of every bundled file will default to the current CodeEditor editability.

**Comment by andreifloricel** [comment]
If it helps, I am ready to implement it myself.

**Comment by danilowoz** [comment]
Hey @andreifloricel! I would totally encourage you to implement it by yourself, and I would be more than happy to guide you through it. But unfortunately, Sandpack is in the middle of a relicensing process, and we can't accept core contributions for the time being.

So, I'll try to spend some time on this, maybe during this week. The `CodeMirror` component already accepts a read-only mode, so it should not be hard to implement it. This is what I have in mind:
- `SandpackCodeEditor` accepts read-only mode;
- Be able to set read-only by file #97;
- Figure out a visual element saying that a file is read-only;

Please, let me know if you have suggestions or requests related to it.

**Comment by andreifloricel** [comment]
Hi @danilowoz,

I agree with the first 2 items, not sure I understand the 3. one (...Figure out a visual element saying that a file is read-only...).
As you said, theoretically it shouldn't be hard to implement it both cases as:
* `CodeMirror` already accepts a read-only
* `SandpackCodeEditor` could just pass a global read-only prop
* file-based read-only should be easy to achieve by checking the `activePath` against the bundled files configuration (the [SandpackBundlerFile](https://github.com/codesandbox/sandpack/blob/v0.12.0/sandpack-client/src/types.ts#L3) would need a new `readOnly` property)
