### ISSUE TITLE
Bug: Could not find module in path

### ISSUE THREAD

**Issue by apostololeg** [codesandbox/sandpack#307]
# Bug report

_Going deeper to using Sandpack in my projects_

## Packages affected

- [ ] sandpack-client _// not tested_
- [x] sandpack-react

## Description

I'm trying to add my library (https://www.npmjs.com/package/@foreverido/uilib) as `dependency`, but get an error:
```
/App.js: Could not find module in path: '@foreverido/uilib/lib/esm/src/components/AssistiveText/AssistiveText.js' relative to '/node_modules/@foreverido/uilib/lib/esm/index.js' (1:0)

> 1 | import { Button } from "@foreverido/uilib";
```

## [> Link to sandbox <](https://codesandbox.io/s/sandpack-project-forked-rvqve?file=/App.js)

_Am I doing something wrong?_

**Comment by apostololeg** [comment]
NPM package `@foreverido/uilib` are contains:
![image](https://user-images.githubusercontent.com/514713/149996283-d9ef8d92-d810-4df5-99cf-a4d4f5346cc1.png)

**Comment by danilowoz** [comment]
Hey @apostololeg. Actually, there's something wrong with your package. Taking a look at `node_modules` content, you can't find the files exported from the entry point: 

<img width="1023" alt="Screenshot 2022-01-19 at 09 23 19" src="https://user-images.githubusercontent.com/4838076/150101537-c27764f5-433c-49a4-a2d0-590f425ab1f2.png">

Hope it helps.
