### ISSUE TITLE
Documentation: Use Monaco in Sandpack

### ISSUE THREAD

**Issue by tromika** [codesandbox/sandpack#327]
Introduce a new guide into [this page](https://sandpack.codesandbox.io/docs/guides) describing how to integrate Monaco editor in place of the CodeMirror. There is already a sandbox already properly working ([here](https://codesandbox.io/s/sandpack-monaco-integration-citxd)), but it would be important to describe how it has been achieved.

There is currently no "official" format for writing guides, so there is room for improvements and suggestions.

**Comment by danilowoz** [comment]
Hey @betomoedano I responded to you on Discord, for any further questions feel free to DM there.
