### ISSUE TITLE
Bug: `editorState` doesn't track code state

### ISSUE THREAD

**Issue by joshwcomeau** [codesandbox/sandpack#332]
# Bug report

## Packages affected

- [ ] sandpack-client
- [x] sandpack-react

## Description of the problem

The `editorState` value found on the `sandpack` instance appears to track whether or not the user has toggled between files, rather than whether they've edited the code:

https://user-images.githubusercontent.com/6692932/151000878-2a5ff0a5-de69-42ef-9662-3aa8226ee913.mp4

It's possible I've misunderstood what `editorState` is meant to track, but it seems like for most use cases, it would be much more valuable to know whether the user has tampered with the code, vs. changed tabs. 

For context: I want to show a little "*" next to the sandbox's title when the user modifies code, so that they know it's been modified. It's important because the sandboxes are in lessons, and the lesson text refers to the original code (eg. "Notice how the text is red"). If the user changes the text from red to yellow, I want to show that the code has been modified, to explain the discrepancy. The code is saved and restored, so they might've modified it in a previous session and forgotten.

### Link to sandbox: 
https://codesandbox.io/s/sandpack-editorstate-demo-mhoyb

### Your Environment

| Software                | Name/Version |
| ----------------------- | ------------ |
| Sandpack-client version | — |
| Sandpack-react version  | 0.13.5 |
| Browser                 | Chrome 97.0 |
| Operating System        | MacOS Monterey |

**Comment by danilowoz** [comment]
Hey @joshwcomeau, thanks for reporting this issue. Indeed, the `editorState` wasn't reliable enough, and hopefully, the new approach makes it better. It should have been fixed on `v0.13.6`

**Comment by joshwcomeau** [comment]
@danilowoz beautiful! I just tested and it works flawlessly. 

Love that it does an actual equality check, rather than just registering changes, so if the user undoes their changes, it flips back to pristine 💯
