### ISSUE TITLE
Consider removing `renderHiddenIframe` from context

### ISSUE THREAD

**Issue by danilowoz** [codesandbox/sandpack#345]
There is a state inside of `sandpackContext,` which looks that hasn't been used in any method or component. So, let's consider removing it and explore the entire codebase looking for any reference and the history of this state.

**Reference**
`renderHiddenIframe`: https://github.com/codesandbox/sandpack/blob/main/sandpack-react/src/contexts/sandpackContext.tsx#L46

**Comment by RishiKumarRay** [comment]
From which files do we have remove all references?

**Comment by danilowoz** [comment]
Hey @RishiKumarRay, I just updated the description, feel free to fix it
