### ISSUE TITLE
Bug: Code change breaks Sandpack due to CORS policy

### ISSUE THREAD

**Issue by jqpe** [codesandbox/sandpack#358]
# Bug report

## Packages affected

-   [x] sandpack-client
    - I haven't tested with the sandpack-client library, but due to the nature of the issue it's plausible that the problem exists there too.
-   [x] sandpack-react

## Description of the problem
When using dependencies, any code changes break the Sandpack as it can not load dependencies because of CORS. The initial render works, but any subsequent changes to the code will break the component. 

**Initial render**
![localhost_3000_posts_material-controls-in-three-js](https://user-images.githubusercontent.com/65775308/152628997-40c27c8d-4768-42cb-a774-952f328e9bdd.png)

**Code change** (scene to scen)
![localhost_3000_posts_material-controls-in-three-js (1)](https://user-images.githubusercontent.com/65775308/152629013-6b31459d-525d-418e-8776-2bef551fb55b.png)

<details>
<summary>Devtools logs; these logs were from https://0-13-7-sandpack.codesandbox.io/ (Sandpack)</summary>
Access to fetch at 'https://data.jsdelivr.com/v1/package/npm/lil-gui' from origin 'https://0-13-7-sandpack.codesandbox.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
</details>

What's more interesting that the log isn't reproducible and I have only received it once. The component breaks every time though.

## What were you doing when the problem occurred?

See above. 

### What steps can we take to reproduce the problem?

- Use native SandpackPreview component 
- Through custom setup provide dependencies
- Change the code and link it to the Sandpack process through SandpackProvider for example.

### Your Environment

| Software                | Name/Version |
| ----------------------- | ------------ |
| Sandpack-client version |    -          |  
| Sandpack-react version  |    0.13.8          |
| Browser                 |  Brave, 1.33.106 Chromium: 96.0.4664.110 (Official Build) (64-bit) |
| Operating System        |     Linux         |

**Comment by DeMoorJasper** [comment]
Could you create/share a minimal reproduction for this please? Can not reproduce this myself

**Comment by jqpe** [comment]
Hey @DeMoorJasper , I have published the code that caused the issue here: https://github.com/jqpe/sandpack-issues-358.

Now I'm getting hit with a different error:
![image](https://user-images.githubusercontent.com/65775308/153166829-4a01141d-1c53-4395-91f7-eff81dfa25cc.png)

It tries to load this url, which doesn't exist: https://unpkg.com/typescript@4.5.5/lib/typescript.js.map.

**Comment by jqpe** [comment]
Here's a CodeSandbox link generated from the same code as in sandpack directory on above repo: https://codesandbox.io/s/be2le?file=/src/main.ts&from-sandpack=true . There it seems to work fine without any complications.

**Comment by DeMoorJasper** [comment]
oh that sourcemap issue is not a sandpack issue, that is typescript not publishing their sourcemaps. Nothing we can really do about that.

The shared example seems to work fine for me, so still can't reproduce it unfortunately

**Comment by jqpe** [comment]
This all is quite odd. The CORS issue seemed like something that is worth investigating, but now I can't reproduce it myself.

Just to clarify: did you run the code in the repository and changed the code? CodeSandbox seems to work (one generated from the code I use in Sandpack) 

Here's the behavior I'm getting when running the example from https://github.com/jqpe/sandpack-issues-358:

https://user-images.githubusercontent.com/65775308/153274254-619f33b1-87cc-45ec-ab9a-498697f2d2db.mp4

Logs for reference:

v652eace1692a40cfa37…439c1639079717194:1 probably doesn't have anything to do with Sandpack as it's just for analytics.

<details>
<summary>Fetch failed loading: POST {PH3} <strong>sandbox.f7d5f9723.js</strong></summary>
<pre>
sandbox.f7d5f9723.js:1 Fetch failed loading: POST {PH3}.
t.persistMeasurements @ sandbox.f7d5f9723.js:1
(anonymous) @ sandbox.f7d5f9723.js:1
c @ vendors~sandbox~sandbox-startup.c2408ad6a.chunk.js:1
(anonymous) @ vendors~sandbox~sandbox-startup.c2408ad6a.chunk.js:1
forEach.t.<computed> @ vendors~sandbox~sandbox-startup.c2408ad6a.chunk.js:1
r @ vendors~sandbox~sandbox-startup.c2408ad6a.chunk.js:1
u @ vendors~sandbox~sandbox-startup.c2408ad6a.chunk.js:1
Promise.then (async)
r @ vendors~sandbox~sandbox-startup.c2408ad6a.chunk.js:1
u @ vendors~sandbox~sandbox-startup.c2408ad6a.chunk.js:1
Promise.then (async)
r @ vendors~sandbox~sandbox-startup.c2408ad6a.chunk.js:1
u @ vendors~sandbox~sandbox-startup.c2408ad6a.chunk.js:1
Promise.then (async)
r @ vendors~sandbox~sandbox-startup.c2408ad6a.chunk.js:1
u @ vendors~sandbox~sandbox-startup.c2408ad6a.chunk.js:1
Promise.then (async)
r @ vendors~sandbox~sandbox-startup.c2408ad6a.chunk.js:1
u @ vendors~sandbox~sandbox-startup.c2408ad6a.chunk.js:1
Promise.then (async)
r @ vendors~sandbox~sandbox-startup.c2408ad6a.chunk.js:1
u @ vendors~sandbox~sandbox-startup.c2408ad6a.chunk.js:1
Promise.then (async)
r @ vendors~sandbox~sandbox-startup.c2408ad6a.chunk.js:1
u @ vendors~sandbox~sandbox-startup.c2408ad6a.chunk.js:1
Promise.then (async)
r @ vendors~sandbox~sandbox-startup.c2408ad6a.chunk.js:1
u @ vendors~sandbox~sandbox-startup.c2408ad6a.chunk.js:1
Promise.then (async)
r @ vendors~sandbox~sandbox-startup.c2408ad6a.chunk.js:1
u @ vendors~sandbox~sandbox-startup.c2408ad6a.chunk.js:1
Promise.then (async)
r @ vendors~sandbox~sandbox-startup.c2408ad6a.chunk.js:1
u @ vendors~sandbox~sandbox-startup.c2408ad6a.chunk.js:1
Promise.then (async)
r @ vendors~sandbox~sandbox-startup.c2408ad6a.chunk.js:1
u @ vendors~sandbox~sandbox-startup.c2408ad6a.chunk.js:1
Promise.then (async)
r @ vendors~sandbox~sandbox-startup.c2408ad6a.chunk.js:1
u @ vendors~sandbox~sandbox-startup.c2408ad6a.chunk.js:1
(anonymous) @ vendors~sandbox~sandbox-startup.c2408ad6a.chunk.js:1
(anonymous) @ vendors~sandbox~sandbox-startup.c2408ad6a.chunk.js:1
ra @ sandbox.f7d5f9723.js:1
na @ sandbox.f7d5f9723.js:1
(anonymous) @ sandbox.f7d5f9723.js:1
c @ vendors~sandbox~sandbox-startup.c2408ad6a.chunk.js:1
(anonymous) @ vendors~sandbox~sandbox-startup.c2408ad6a.chunk.js:1
forEach.t.<computed> @ vendors~sandbox~sandbox-startup.c2408ad6a.chunk.js:1
r @ vendors~sandbox~sandbox-startup.c2408ad6a.chunk.js:1
u @ vendors~sandbox~sandbox-startup.c2408ad6a.chunk.js:1
(anonymous) @ vendors~sandbox~sandbox-startup.c2408ad6a.chunk.js:1
(anonymous) @ vendors~sandbox~sandbox-startup.c2408ad6a.chunk.js:1
aa @ sandbox.f7d5f9723.js:1
ia @ sandbox.f7d5f9723.js:1
la @ sandbox.f7d5f9723.js:1
(anonymous) @ sandbox.f7d5f9723.js:1
c @ vendors~sandbox~sandbox-startup.c2408ad6a.chunk.js:1
(anonymous) @ vendors~sandbox~sandbox-startup.c2408ad6a.chunk.js:1
forEach.t.<computed> @ vendors~sandbox~sandbox-startup.c2408ad6a.chunk.js:1
r @ vendors~sandbox~sandbox-startup.c2408ad6a.chunk.js:1
u @ vendors~sandbox~sandbox-startup.c2408ad6a.chunk.js:1
(anonymous) @ vendors~sandbox~sandbox-startup.c2408ad6a.chunk.js:1
(anonymous) @ vendors~sandbox~sandbox-startup.c2408ad6a.chunk.js:1
(anonymous) @ sandbox.f7d5f9723.js:1
(anonymous) @ default~sandbox~sandbox-startup.d73a8c31a.chunk.js:1
I @ default~sandbox~sandbox-startup.d73a8c31a.chunk.js:1
D @ default~sandbox~sandbox-startup.d73a8c31a.chunk.js:1
</pre>
</details>

**Comment by jqpe** [comment]
Closing this as the CORS error couldn't be reproduced.
