### ISSUE TITLE
Disable SandpackReactDevTools?

### ISSUE THREAD

**Issue by ndom91** [codesandbox/sandpack#359]
# Bug report

## Packages affected

-   [ ] sandpack-client
-   [x] sandpack-react

## Description of the problem

I'm trying to insert a Sandpack instance into a [Docusaurus](https://docusaurus.io) page. 

First things first, they only support MDX v1, I don't know if thats an issue.

However, when trying to import and use the `<Sandpack />` component, I get an error, that webpack can't resolve `scheduler` in the `react-devtools-inline` package.

```
Compiled with problems:X

ERROR in ./node_modules/react-devtools-inline/dist/frontend.js 27413:17-37

Module not found: Error: Can't resolve 'scheduler' in '/opt/next-auth/next-auth/packages/docs/node_modules/react-devtools-inline/dist'
```

I was wondering if there is a way to just disable the import / usage of the inline devtools part as a whole?

I've tried to use Sandpack via the custom options, by just importing a few select pieces (Layout, Preview, etc.), but that still appears to try to import from `react-devtools-inline` and I get the same error message.

For example:

```jsx
import {
  SandpackProvider,
  SandpackLayout,
  SandpackCodeEditor,
  SandpackPreview,
} from "@codesandbox/sandpack-react";

const CustomSandpack = () => (
  <SandpackProvider template="react">
    <SandpackLayout>
      <SandpackCodeEditor />
      <SandpackPreview />
    </SandpackLayout>
  </SandpackProvider>
);
```

Also with `template="vue"`, I get the same error message. Seems `react-devtools-inline` is probably unnecessary if the user is working on a Vue based codesandbox, no?

Or maybe the inline-devtools package is more critical to Sandpack as a whole than I imagine.

I'm using:

- `@codesandbox/sandpack-react: 0.13.10`
- `@docusaurus/core: 2.0.0-beta-9`
- Brave 1.30.89 (Chromium: 94)
- Arch Linux

**Comment by danilowoz** [comment]
Hey @ndom91, thanks for reporting this issue. But actually, the `react-devtools-inline` dependency will only be loaded if you're using the SandpackReactDevTools, is that the case? Also, could you please provide a sandbox reproducing this error? It gave it a try it worked as expected, see the sandbox below:

Code: https://codesandbox.io/s/docusaurus-example-tq9zk?file=/src/components/CustomSandpack.jsx
Preview: https://tq9zk.sse.codesandbox.io/docs/intro

@ndom91 I noticed you're trying to implement Sandpack in NextAuthjs documentation right? I'm afraid Sandpack might not work for your project, as currently, Sandpack doesn't support SSE projects - see more details [here](https://sandpack.codesandbox.io/docs/faq#does-sandpack-support-nextjs-or-other-server-side-applications), hopefully, we can support it in the future, but it's not in our plans in the mid term.

**Comment by ndom91** [comment]
Hey @danilowoz thanks for the thorough answer! Yes, I'm trying to implement it for the NextAuth.js docs, but only for our "custom page" feature. So the users can play around with the options and see how detailed / customizable the page is and decide whether they wanna stick with our simple built-in ones or go right to making their own.

Very strange, I tried a custom implementation like in your example above. 

Basically exactly this:

```js
import React from "react";
import {
  SandpackProvider,
  SandpackLayout,
  SandpackCodeEditor,
  SandpackPreview
} from "@codesandbox/sandpack-react";

export const CustomSandpack = () => (
  <SandpackProvider template="react">
    <SandpackLayout>
      <SandpackCodeEditor />
      <SandpackPreview />
    </SandpackLayout>
  </SandpackProvider>
);

```

And I still got errors regarding the `react-devtools-inline` package :thinking: 

Will double check all this and get back to you. Thanks again!

**Comment by ndom91** [comment]
@danilowoz yeah still the same issue. This is my setup:

The MDX page:

![image](https://user-images.githubusercontent.com/7415984/152873587-88d6a8ca-aa92-496c-8e51-950454dadc6a.png)


The Sandpack component:

![image](https://user-images.githubusercontent.com/7415984/152873620-28f7c0c9-c9b4-43d8-be0b-a7de12669af9.png)

Just using your example 1:1 for testing. 

The outcome:

![image](https://user-images.githubusercontent.com/7415984/152873668-47c5b319-5fb0-4692-9fb4-4383d178876d.png)

As you can see, behind the darkened background of the error overlay, you can see that Sandpack has rendered. The css seems to be missing, but I probably just need to manually import it, as your docs clearly say. Anyway, the `react-devtools-inline` error still seems to be there :thinking:

**Comment by danilowoz** [comment]
That's weird, maybe there is something wrong if your local environment? I opened a PR integrating Sandpack and I left an example there: https://github.com/nextauthjs/next-auth/pull/3880

<img width="1199" alt="Screenshot 2022-02-08 at 10 12 19" src="https://user-images.githubusercontent.com/4838076/152966205-c87b38fa-45f2-485c-ada6-2024db16bbbc.png">

As I was able to make it work properly, I'm going to close this issue - feel free to reopen it in case you face another problem.
