### ISSUE TITLE
Add onFocus & onBlur props to SandpackCodeEditor 

### ISSUE THREAD

**Issue by bradwoods** [codesandbox/sandpack#360]

**Comment by danilowoz** [comment]
Hey @bradwoods, here's an example of how you can implement it by yourself. To sum up, CodeMirror (which we use in the SandpackCodeEditor) encourages to use DOM listeners to do it, and currently, Sandpack doesn't support it officially (if we might consider supporting it in case more request like yours shows up here).
 
https://codesandbox.io/s/sandpack-onblur-onfocus-ccx8k?file=/src/App.js

**Comment by bradwoods** [comment]
hey mate, thanks for the examples. Sounds good.
