### ISSUE TITLE
Documentation: get codemirror instance 

### ISSUE THREAD

**Issue by danilowoz** [codesandbox/sandpack#363]
Create a piece of documentation explaining how to get the CodeMirror instance and what is the benefits, example:
```jsx
const editorRef = useRef<CodeEditorRef>(null);

  useEffect(() => {
    const editorElement = editorRef.current?.getCodemirror();
    if (!editorElement) return;

    if (animationComplete && !editorElement.hasFocus) {
      editorElement.focus();

      const newState = editorElement.state.update({
        selection: { anchor: 322 },
      });

      if (newState) {
        editorElement.update([newState]);
      }
    }
  }, [animationComplete, editorRef]);

<SandpackCodeEditor ref={editorRef} />
```

**Comment by sauron918** [comment]
Tried this example and always get editorElement as `undefined`: https://codesandbox.io/s/busy-field-2gw3nc?file=/src/App.js

**Comment by holdenmatt** [comment]
Just FYI for anyone else who finds this issue.

If you follow the docs, the codemirror ref is always undefined (I think it's a timing issue):
https://sandpack.codesandbox.io/docs/advanced-usage/components#advanced-usage

I found two options to fix it.

1. If you set initMode='immediate' on the editor, the ref will work (but that may have other perf implications).

2. You can wrap the editor in a div and use an intersection observer, similar to what they do here (that's what I ended up doing):
https://github.com/codesandbox/sandpack/blob/7d60a4334980eef304d53b1c3df371ed6dbcf491/website/landing/components/Intro/Sections/Custom.tsx#L57
