### ISSUE TITLE
Blinking cursor location gets reset when replacing Editor content using prettier

### ISSUE THREAD

**Issue by MintBerrry** [codesandbox/sandpack#371]
# Bug report

## Packages affected

-   sandpack-react

## Description of the problem

When replacing the content of the editor using `prettier`, the position of the blinking cursor gets reset to the beginning of the Editor.

### What steps can we take to reproduce the problem?

- Open sandbox below
- replace Editor content with `{}` (or any code)
- notice blinking cursor is now at beginning of editor

### Link to sandbox: [sandpack-prettier](https://codesandbox.io/s/sandpack-prettier-1po91?file=/src/App.js:1497-1515)

Is this a bug or is there a way to add a ref to the Editor input and move the blinking cursor location after replacing content? 

Update: It looks like this is possible https://github.com/codesandbox/sandpack/issues/363

**Comment by danilowoz** [comment]
Hey, I spent some time trying to fix it, and fortunately, I made it! 
Let me know if works for you
