### ISSUE TITLE
Performance/refactor: evaluate possible improvements on `componentDidUpdate`

### ISSUE THREAD

**Issue by danilowoz** [codesandbox/sandpack#379]
Currently, a lot of operations are being done in the `componentDidUpdate`, and as Dan mentioned on #377 this is a pattern that must be avoided, in order to prevent nested updates. So, we need to find out how to improve this method and address other performances issues that this might be causing.

I haven't gone any further and haven't collected evidence of any performance issues, but as the current implementation doesn't follow a proper react pattern, it's expected that it may have some issues to be addressed.

**Comment by danilowoz** [comment]
Hey, thanks for taking a look at this issue. However, we're moving from class component to hook-based components on https://github.com/codesandbox/sandpack/pull/607, which should fix this issue.

**Comment by griimick** [comment]
Great! Makes sense.
