### ISSUE TITLE
Codesnippet goes missing on `cmd + x` (cutting) on selecting them. 

### ISSUE THREAD

**Issue by harish-sethuraman** [codesandbox/sandpack#382]
# Bug report

## Packages affected

-   [x] sandpack-client
-   [ ] sandpack-react

## Description of the problem

When the code inside of the code viewer is selected and `cmd + x` is pressed the code goes missing. 

### What steps can we take to reproduce the problem?
- Go to: https://sandpack.codesandbox.io/docs/advanced-usage/components#code-viewer
- select code and press `cmd + x`

https://user-images.githubusercontent.com/32865581/154813151-5509a734-88cc-4f9b-8e9f-72d3e5bf71d6.mov

**Comment by danilowoz** [comment]
Ohhhh, let's fix it as soon as possible!
