### ISSUE TITLE
CodeMirror plugin crashed: Error: Ranges must be added sorted by `from` position and `startSide`

### ISSUE THREAD

**Issue by Jokcy** [codesandbox/sandpack#383]
# Bug report

## Packages affected

-   [ ] sandpack-client
-   [x] sandpack-react

sandpack-client not test

## Description of the problem

Decorators will fail when use inline decorators with line number small then 10.

https://codesandbox.io/s/sandpack-project-forked-vzf788?file=/data.js

See this sandbox, open the console you will see an error `CodeMirror plugin crashed: Error xxxxx`. But if you update the `line` property to 12, it will work fine.

### Link to sandbox: [link]() (optional)

https://codesandbox.io/s/sandpack-project-forked-vzf788?file=/data.js

### Your Environment

| Software                | Name/Version |
| ----------------------- | ------------ |
| Sandpack-client version |             |
| Sandpack-react version  |      latest        |
| Browser                 |       chrome       |
| Operating System        |      mac        |

**Comment by danilowoz** [comment]
Hey @Jokcy, thanks for reporting this issue! 

It's a very interesting bug because CodeMirror needs an array sorted by the key `line`, so the following example should work:

```js
export default [
  { className: "highlight", line: 1 },
  {
    className: "widget",
    elementAttributes: { "data-id": "1" },
    line: 8, // Moved to between 1 and 9
    startColumn: 3,
    endColumn: 7
  },
  { className: "highlight", line: 9 }
];

```

I think we can easily fix it on the Sandpack side, would you like to give it a try?

**Comment by Jokcy** [comment]
@danilowoz Yeah I would like to have a try, I will give some feedback soon.
