### ISSUE TITLE
React should be a dev dependency and a peer dependency NOT a dependency 

### ISSUE THREAD

**Issue by joepuzzo** [codesandbox/sandpack#387]
# Bug report

## Packages affected

-   sandpack-react

## Description of the problem

You have react as  "react": "^17.0.2", in dependencies

This will make 17 get installed and mis matching deps will occur. We are still on v16 of react and this breaks our storybook docs due to this issue https://github.com/storybookjs/storybook/issues/17161. 

## Solution

please move react to a PEER and DEV dependency. And keep it out of normal `dependencies`

**Comment by danilowoz** [comment]
Hey, I think there is a misunderstanding here, because sandpack-react doesn't have react as `dependency` but as a `peer-dependency`: https://github.com/codesandbox/sandpack/blob/main/sandpack-react/package.json#L81-L84

**Comment by joepuzzo** [comment]
hmm maybe I had old version

**Comment by danilowoz** [comment]
I'm going to assume this has been solved, feel free to reopen it if necessary.
