### ISSUE TITLE
Pages using the `Sandpack` component are generating 2 history entries on Firefox

### ISSUE THREAD

**Issue by noobinthisgame** [codesandbox/sandpack#398]
# Bug report

## Packages affected

-   [ ] sandpack-client
-   [x] sandpack-react

## Description of the problem

Hi ! 
while working on the ChakraUI docs and navigating through them I noticed that when I was using Firefox I had to go back twice in the history after visiting a page where we used Sanpack as Component.
This behaviour did appear on Chrome or Safari.

### What steps can we take to reproduce the problem?

1. Open Firefox
2. Go to https://chakra-ui.com/ 
3. You can see that you can go back twice in the page history
4. Go to https://chakra-ui.com/docs/components/recipes/floating-labels
5. Same behvaviour

### Link to sandbox: [link]() (optional)

Code of ChakraUI docs is open source https://github.com/chakra-ui/chakra-ui-docs

### Your Environment

| Software                | Name/Version |
| ----------------------- | ------------ |
| Sandpack-client version |      -        |
| Sandpack-react version  |      "0.13.11"      |
| Browser                 |        Firefox 95.0.2 and 97.0.1     |
| Operating System        |       Windows / MacOS       |

**Comment by danilowoz** [comment]
Searching about this bug, I've found a couple of useful links:
- Possible solution: https://github.com/aFarkas/lazysizes/commit/512800de6ebddf6a5000624b67f86c4f0d77d8c6
- More details: https://stackoverflow.com/questions/2245883/browser-back-acts-on-nested-iframe-before-the-page-itself-is-there-a-way-to-av

**Comment by noobinthisgame** [comment]
Thanks for solving this so quickly!! :)
