### ISSUE TITLE
Changing default environment

### ISSUE THREAD

**Issue by pomber** [codesandbox/sandpack#40]
I'm trying to load in sandpack the same files as in this csb: https://codesandbox.io/s/test-parcel-environment-b7uf3

This is what I'm trying: https://codesandbox.io/s/sandpack-test-parcel-environment-7yjt2?file=/src/App.js

But apparently it's using the `create-react-app` environment even when I'm passing `environment: 'parcel'`. 

Am I missing something or is it a bug?

**Comment by pomber** [comment]
Well, it's using `create-react-app` even when I use the vanilla template:
```jsx
export default function App() {
  return <SandpackRunner template="vanilla" />;
}
```

When I click the "Open in CodeSandbox" button, it shows:
<img src="https://user-images.githubusercontent.com/1911623/115149044-9ac2c300-a038-11eb-8ef6-1810339559e5.png" width="300"/>

Not sure if that's intentional.

**Comment by alexnm** [comment]
this is codesandbox determining the environment based on the input files. for generating the sandbox via the link we only pass the files, no meta information about environment. but I'm looking into the parcel/vanilla setup to see why your first example doesn't work

**Comment by pomber** [comment]
Not sure if it is related to the environment, but when I try a sandpack that is just an HTML loading an external script, the script doesn't load. I tried several things and couldn't make it work.

**Comment by alexnm** [comment]
this is a limitation of the current bundler, I'll make a new issues tomorrow explaining the exact situation. currently we cannot execute code that is passed in the head tag of the entry html file

**Comment by pomber** [comment]
> this is a limitation of the current bundler, I'll make a new issues tomorrow explaining the exact situation. currently we cannot execute code that is passed in the head tag of the entry html file

Same happens if I move the script from the head to the body. Any workaround to load an external script from the HTML?

**Comment by alexnm** [comment]
We probably need to change the implementation in the bundler, the body is replaced with the body of the HTML page, but scripts are not executed this way.
