### ISSUE TITLE
sandbox.config-like configuration for sandpack-react

### ISSUE THREAD

**Issue by sedghi** [codesandbox/sandpack#404]
# Tell us how you think we can improve Sandpack
Based on my understanding sandpack-client has configuration for properties such as `infiniteLoopProtection` but not the `sandpack-react`

## Packages affected

-   [ ] sandpack-client
-   [x] sandpack-react

## What is this feature?
It allows for configuration similar to codeSandbox

## How would your idea work?
Similar to sandback-client that now supports it

**Comment by danilowoz** [comment]
Hey! Currently, Sandpack React doesn't have this option. But if you want you can pass a `sandbox.config` and it'll work properly, for example: 

```jsx
<Sandpack
  files={{
    "/sandbox.config.json": `{ "hardReloadOnChange" :  true }`,
  }}
/>
```

You can find all options here https://codesandbox.io/docs/configuration#sandbox-configuration

Hope it helps
