### ISSUE TITLE
Sandpack preview not updating when files change (svelte environment)

### ISSUE THREAD

**Issue by pomber** [codesandbox/sandpack#41]
See this codesandbox: https://codesandbox.io/s/sandpack-test-svelte-c1by1?file=/src/App.js

When the files change (click the "change code" button) the preview is not updated (but it updates when you click the little refresh button).

**Comment by alexnm** [comment]
this is interesting, looks like it might be related with hmr inside svelte, I'm not familiar with how it works, will have to check with @CompuIves

**Comment by pomber** [comment]
Thanks @DeMoorJasper. Is the fix in v0.0.4?

**Comment by DeMoorJasper** [comment]
No it's only fixed on codesandbox for now

cc @alexnm could you deploy a new version?

**Comment by alexnm** [comment]
yes, I'll get a 0.0.5 today

**Comment by alexnm** [comment]
@pomber 0.0.5 is now on npm, including the fix for svelte

**Comment by pomber** [comment]
thank you both! it works
