### ISSUE TITLE
No "children" attribute for SandpackProviderProps 

### ISSUE THREAD

**Issue by rahul1** [codesandbox/sandpack#462]
# Bug report

## Packages affected

-   [ ] sandpack-client
-   [x] sandpack-react

## Description of the problem

I copied the following code snippet directly from the documentation
```ts
    <SandpackProvider template="react">
      <SandpackLayout>
        <SandpackCodeEditor />
        <SandpackPreview />
      </SandpackLayout>
    </SandpackProvider>
```
However, I got the following error. I think this is because there is no attribute `children` in the type definition `SandpackProviderProps`. Let me know if I'm missing anything

```
Type '{ children: Element; template: "react"; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<SandpackProvider> & Pick<Readonly<SandpackProviderProps>, "template" | ... 9 more ... | "externalResources"> & InexactPartial<...> & InexactPartial<...>'.
  Property 'children' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<SandpackProvider> & Pick<Readonly<Sandpack
```

### What steps can we take to reproduce the problem?

See my code snippet above

### Your Environment

| Software                | Name/Version |
| ----------------------- | ------------ |
| Sandpack-client version |     0.19.6         |
| Sandpack-react version  |      0.19.6        |
| Browser                 |      Chrome        |
| Operating System        |     MacOS         |

**Comment by SlexAxton** [comment]
Also experiencing this one 🙏

**Comment by SlexAxton** [comment]
Happens on `SandpackThemeProvider` as well.

**Comment by danilowoz** [comment]
Hey, which React version are you using? Could you please provide sandbox which reproduces this error?

Thanks

**Comment by danilowoz** [comment]
Addressed on https://github.com/codesandbox/sandpack/pull/375
