### ISSUE TITLE
update code mirror 0.20

### ISSUE THREAD

**Issue by sheeeeep** [codesandbox/sandpack#468]
# Tell us how you think we can improve Sandpack

## Packages affected

-   [ ] sandpack-react

## What is this feature?
update code mirror 0.20

## How would your idea work?
I have other code editor in my project, which use 0.20. They made conflicts and errors.

**Comment by danilowoz** [comment]
I tried to upgrade all CodeMirror dependencies, but I faced a few problems, probably due to some breaking changes. If you can, I recommend trying to match the Sandpack dependencies version. 

In the future, I'll try to spend more time addressing it.
