### ISSUE TITLE
Feature request for NextJS and NuxtJS support in sandpack

### ISSUE THREAD

**Issue by shivamfromCOMETLABS** [codesandbox/sandpack#478]
# Tell us how you think we can improve Sandpack

## Packages affected

-   [ ] sandpack-client
-   [ ✔️] sandpack-react

## What is this feature?
NextJS, NuxtJS templates can be added to the library

## How would your idea work?
NextJS, NuxtJS will be available to the user to use

## Do you have any examples of how you would like to see us implement it?
It would work just like the other pre-built templates do

**Comment by danilowoz** [comment]
Hey, thanks for letting us know about your interest in this feature. You can find our current position on this topic here: https://github.com/codesandbox/sandpack/discussions/253

Hope it helps
