### ISSUE TITLE
Update babel in environment: "parcel"

### ISSUE THREAD

**Issue by azu** [codesandbox/sandpack#481]
# Bug report

## Packages affected

-   [ ] sandpack-client
-   [x] sandpack-react

## Description of the problem

When I use Private Fields in `environment: "parcel"`,  preview throw an error.

```
/src/index.js: Unexpected character '#' (2:2)

  1 | class App {
> 2 |   #privateField = 1111;
    |  ^
  3 | }
  4 | console.log(new App());
```

Probably, babel-env is outdated?

babel-env support private fields in 7.10.0.

- [7.10.0 Released: Class Fields in preset-env, '#private in' checks and better React tree-shaking · Babel](https://babeljs.io/blog/2020/05/25/7.10.0)

https://1-0-4-sandpack.codesandbox.io/static/js/babel.6.26.min.js is used.

## What were you doing when the problem occurred?

I write private fields synbol `#` and get an error.

### What steps can we take to reproduce the problem?

```jsx
import { Sandpack } from "@codesandbox/sandpack-react";

const APP_CODE = `
class App {
  #privateField = 1111;
}
console.log(new App());
`.trim();

export default function App() {
  return (
    <Sandpack
      customSetup={{
        environment: "parcel",
        files: {
          "/src/index.js": {
            code: APP_CODE
          }
        }
      }}
      template="vanilla"
    />
  );
}
```

### Link to sandbox: [link]() (optional)

https://codesandbox.io/s/sandpack-parcel-es2022-forked-tgk89o?file=/src/index.js

### Your Environment

| Software                | Name/Version |
| ----------------------- | ------------ |
| Sandpack-client version |              |
| Sandpack-react version  |        1.0.4      |
| Browser                 |       Firefox/Chrome       |
| Operating System        |              |

Maybe Related

- https://github.com/codesandbox/sandpack/issues/137

As a context, I want to use native ES2022 syntax in sandpack.
But, sandpack transpile the code by babel.

**Comment by danilowoz** [comment]
@DeMoorJasper do you think can we support this on bundler v1? or maybe on v2?

**Comment by DeMoorJasper** [comment]
@danilowoz Skipping babel transpilation no, but updating babel probably. Already works with v2

**Comment by danilowoz** [comment]
@azu would you mind using the new bundler? It should work fine
```jsx
<Sandpack options={{ bundlerURL: "https://83c59996.sandpack-bundler.pages.dev/" }} />
```

**Comment by azu** [comment]
Thanks!

I've confirmed that private class fields works with new bundler
https://codesandbox.io/s/sandpack-parcel-es2022-with-new-bundler-m8vvv1?file=/src/App.js
<img width="1533" alt="image" src="https://user-images.githubusercontent.com/19714/172278411-1cc83b33-0fb6-4a88-b9ce-dd07e62c4ec5.png">
