### ISSUE TITLE
SandpackFileExplorer show hidden files

### ISSUE THREAD

**Issue by azu** [codesandbox/sandpack#482]
# Bug report

## Packages affected

-   [ ] sandpack-client
-   [x] sandpack-react

## Description of the problem

`<SandpackFileExplorer>` show hidden files

## What were you doing when the problem occurred?

I expected that SandpackFileExplorer shows only `/index.js` and `/index2.js`.
It means that only show same files with Tab files.

But actually, SandpackFileExplorer shows `/src/index.js`, `/hidden.js` and vinilla template files.

<img width="1392" alt="image" src="https://user-images.githubusercontent.com/19714/170853475-a119b023-24fb-4f6e-8bf8-32fc6e77da7b.png">

```tsx
import {
  SandpackProvider,
  SandpackLayout,
  SandpackFileExplorer,
  SandpackCodeEditor
} from "@codesandbox/sandpack-react";

export default function App() {
  return (
    <SandpackProvider
      files={{
        "/index.js": {
          code: "// index.js",
          active: true
        },
        "/index2.js": {
          code: "// index2.js"
        },
        "/src/index.js": {
          code:
            "// this file is generated by vanilla template, but it is not needed",
          hidden: true
        },
        "/hidden.js": {
          code: "// hidden.js",
          hidden: true
        }
      }}
      customSetup={{
        entry: "/index.js"
      }}
      template={"vanilla"}
    >
      <SandpackLayout>
        <SandpackFileExplorer />
        <SandpackCodeEditor />
      </SandpackLayout>
    </SandpackProvider>
  );
}
```

### What steps can we take to reproduce the problem?

I just use SandpackFileExplorer + `hidden` property.
I think that `options.visibleFiles` is same behavior

### Link to sandbox: [link]() (optional)

https://codesandbox.io/s/sandpack-parcel-sandpackfileexplorer-hidden-ejzfhy?file=/src/App.js

### Your Environment

| Software                | Name/Version |
| ----------------------- | ------------ |
| Sandpack-client version |              |
| Sandpack-react version  |     1.0.4         |
| Browser                 |      Firefox/Chrome        |
| Operating System        |              |

**Comment by jerrywu001** [comment]
Personally, I don't think it's a bug, my scene needs to show all the files in the file tree, just hide them in tabs.

My solution is to provide a property that indicates whether files in the file tree are automatically hidden.LIke this:

```jsx
// enableAutoHiddenFile: boolean; // default: false
<SandpackProvider
    files={{
      "/index.js": {
        code: "// index.js",
        active: true
      },
      "/index2.js": {
        code: "// index2.js"
      },
      "/src/index.js": {
        code:
          "// this file is generated by vanilla template, but it is not needed",
        hidden: true
      },
      "/hidden.js": {
        code: "// hidden.js",
        hidden: true
      }
    }}
    customSetup={{
      entry: "/index.js"
    }}
    template={"vanilla"}
  >
    <SandpackLayout>
      <SandpackFileExplorer enableAutoHiddenFile={true} />
      <SandpackCodeEditor />
    </SandpackLayout>
  </SandpackProvider>
```
