### ISSUE TITLE
Can we add a new template for vue-vite ?

### ISSUE THREAD

**Issue by jerrywu001** [codesandbox/sandpack#484]
Can we add a new template for **vue-vite** ?

**Comment by danilowoz** [comment]
Yeah, I think we can.
- @jerrywu001 do you have any template/sandbox/preset in mind? What are the minimal configuration files we need to run such a template?
- @DeMoorJasper I guess the current bundler supports Vite, right? I saw that it's `vue-cli` as environment

**Comment by jerrywu001** [comment]
> @jerrywu001 do you have any template/sandbox/preset in mind? What are the minimal configuration files we need to run such a template?

Same as the vue3 preset, then turn the environment into vite
