### ISSUE TITLE
SandpackThemeProvider undoing global styles 

### ISSUE THREAD

**Issue by mayank99** [codesandbox/sandpack#489]
I noticed that when using the default dark theme, the scrollbars for the code editor were still showing in light mode, even though I specify `color-scheme: dark` in my global styles.

Debugging a little, I traced the cause to this line:
https://github.com/codesandbox/sandpack/blob/163c66ba218ce606cf814d3b625a7132f76cad55/sandpack-react/src/contexts/themeContext.tsx#L16

Perhaps this should instead be `all: unset` or `all: revert`? `initial` will reset everything to the browser default value, _even for inherited properties._

**Comment by danilowoz** [comment]
Hey @mayank99, thanks for letting us know about this issue.

Afraid of setting another value to `all` might introduce breaking changes to the Sandpack layout. So I took another approach on #491 and I infer what is the theme type from the main surface color of the palette colors, then I set the most suitable `color-scheme` for the given theme. 

Let me know what you think.

**Comment by mayank99** [comment]
Hi @danilowoz, thanks for looking into this.

Will your solution specify the correct scrollbar color for `@codesandbox/sandpack-themes` or only the default light and dark themes? If it works for the additional themes, that should be good I think.

**Comment by danilowoz** [comment]
It would work for any theme, regardless if it's a default or custom
