### ISSUE TITLE
Codemirror: RangeError Selection points outside of document

### ISSUE THREAD

**Issue by danilowoz** [codesandbox/sandpack#505]
### Discussed in https://github.com/codesandbox/sandpack/discussions/501

<div type='discussions-op-text'>

<sup>Originally posted by **grikomsn** June 18, 2022</sup>
Recently migrated my Next.js side project from using sandpack v0 to v1[^1] and noticed that for some reason it errors out in production but works on development. Below are screenshots with console logs for both instances.

Besides the console log errors, line numbers do not show and editor is not clickable nor editable. Will attempt debugging whether it's from the UI library or something else.

**Development**

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/8220954/174433187-4974ba4f-aa2e-4c28-82f4-eec0602b4085.png">

**Production**

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/8220954/174433196-c7ba5532-c5d5-4301-b25f-105dddd1a774.png">

[^1]: https://github.com/grikomsn/patterns-run/commit/51e7fd73145e37bff4667796793bf4e631f28e72#diff-55de525accdc1569db9c81113d77df271e051f7c8b9dc882d5268043346a18df</div>

https://github.com/codesandbox/sandpack/issues/465

**Comment by danilowoz** [comment]
Some findings: It seems that Nextjs is compiling the codemirror/state with different outputs:
**Wrong**
<img width="349" alt="Screenshot 2022-06-20 at 10 49 18" src="https://user-images.githubusercontent.com/4838076/174583802-ce7e4db5-1f81-4a2e-a70d-8d2372f536ae.png">

**Correct**
<img width="263" alt="Screenshot 2022-06-20 at 11 34 32" src="https://user-images.githubusercontent.com/4838076/174583794-8512d8f6-cee9-4ebd-8cb9-cddf5fe094fe.png">

**Comment by grikomsn** [comment]
Tried disabling `swcMinify` and it (surprisingly) works[^1]. Thank you for the insight! Might need to reconsider enabling `swcMinify` for current and future projects.

[^1]: https://github.com/grikomsn/patterns-run/commit/b0ad10f8a2059913b8896aa82008b2c150178e30
