### ISSUE TITLE
Nothing renders, (0 , import_core.createStitches) is not a function

### ISSUE THREAD

**Issue by bradwoods** [codesandbox/sandpack#508]
# Bug report
-   [ ] sandpack-client
-   [x] sandpack-react

- Following instructions to install: https://sandpack.codesandbox.io/docs/getting-started/install
- Nothing renders. Error message: `(0 , import_core.createStitches) is not a function`
- TypeScript also reporting `Module '"@codesandbox/sandpack-react"' has no exported member 'Sandpack'.`

[link](https://stackblitz.com/edit/react-ts-ynm1gl?file=index.tsx)

**Comment by danilowoz** [comment]
Hey, I don't think it's a Sandpack problem. It seems that Stackblitz is not resolving the types and Sandpack dependencies. 

Here's an example working, same thing if you run it locally https://codesandbox.io/s/keen-morning-cwooqe

Hope it helps 😀

**Comment by bradwoods** [comment]
You're right. Thanks for checking it out.
