### ISSUE TITLE
Support more templates

### ISSUE THREAD

**Issue by uyarn** [codesandbox/sandpack#52]
Hi, is there any plan to support more template, such as vue3, angular? or PR welcome?

**Comment by alexnm** [comment]
Templates are now hardcoded here: https://github.com/codesandbox/sandpack/tree/main/sandpack-react/src/templates so any contribution is welcome. However, I'll soon work on integrating the codesandbox API to fetch any public template/sandbox in sandpack, so hardcoded templates will be discarded.

**Comment by uyarn** [comment]
got it, thanks for your reply ~ @alexnm

**Comment by nkovacic** [comment]
Will next.js without server rendering be supported as a template? I know it supported on codesandbox, but it requires containers.

**Comment by alexnm** [comment]
@nkovacic no, that's not possible with sandpack, as we are running the browser bundler only
