### ISSUE TITLE
Property 'run' is missing in type 'readonly KeyBinding[]' but required in type 'KeyBinding'.ts(2741)

### ISSUE THREAD

**Issue by NekoChanTaiwan** [codesandbox/sandpack#538]
# Bug report

## Packages affected

-   [ ] sandpack-client
-   [x] sandpack-react

## Description of the problem

![image](https://user-images.githubusercontent.com/47508893/180107006-f7a99ccb-30ea-418f-9460-a3f9754c8323.png)

### What steps can we take to reproduce the problem?

https://codesandbox.io/s/sandpack-extensions-error-demo-e1utgn?file=/src/App.tsx ( needs to refresh when dependencies is installed. )

### Your Environment

| Software                | Name/Version |
| ----------------------- | ------------ |
| Sandpack-client version |              |
| Sandpack-react version  | 1.3.0             |
| @codemirror/autocomplete | 6.1.0             |
| Browser                 | Edge             |
| Operating System        | Windows 11             |

**Comment by danilowoz** [comment]
Yeah, the type errors are not useful at all.

As Sandpack needs a flat array to consume the keybinding and shallow and compare differences between renders, I'd recommend you merge the extension keymap in to the array prop, like the example bellow:

```
<SandpackCodeEditor
  extensions={[autocompletion()]}
  extensionsKeymap={[...completionKeymap]}
/>
```

If this problem persists, or if it becomes more often, I'll properly address this at the Sandpack component level.

**Comment by NekoChanTaiwan** [comment]
> Yeah, the type errors are not useful at all.
> 
> As Sandpack needs a flat array to consume the keybinding and shallow and compare differences between renders, I'd recommend you merge the extension keymap in to the array prop, like the example bellow:
> 
> ```
> <SandpackCodeEditor
>   extensions={[autocompletion()]}
>   extensionsKeymap={[...completionKeymap]}
> />
> ```
> 
> If this problem persists, or if it becomes more often, I'll properly address this at the Sandpack component level.

Thx for reply, but I still got the error :
![image](https://user-images.githubusercontent.com/47508893/180178192-1189ed6c-8699-4487-b685-6505572851cc.png)

In my VSCode it will show the type error :
![image](https://user-images.githubusercontent.com/47508893/180178363-6ba36854-83c2-4e91-8557-8b5f74c32b17.png)

**Comment by danilowoz** [comment]
Please use `@codemirror/autocomplete@0.19.15`, as Sandpack hasn't updated yet the for the latest CodeMirror version, and this might cause some conflicts. Here's a screenshot working with the proper dependency version:
![Screenshot 2022-07-21 at 10 41 52](https://user-images.githubusercontent.com/4838076/180183223-c84e592f-6b99-4cac-80c6-f28cdbcaeed5.png)
