### ISSUE TITLE
Documentation: Prettier example

### ISSUE THREAD

**Issue by davidbani** [codesandbox/sandpack#543]
The Prettier CodeSandbox example in "Guides Overview" is broken when editing code outside of `export`:

* Guide: https://sandpack.codesandbox.io/docs/guides/guides-overview
* Prettier CodeSandbox: https://codesandbox.io/s/sandpack-prettier-1po91?file=/src/App.js

Error: `RangeError Selection points outside of document`

**Comment by danilowoz** [comment]
Hey, thanks for letting me know.
I updated the dependencies and it should be fixed
