### ISSUE TITLE
Documentation: How I can import CSS files in Angular project?

### ISSUE THREAD

**Issue by WangJiaoJo** [codesandbox/sandpack#563]
Hi,

I want to include the primeng library into the Angular project, and it requires to import 'node_modules/primeng/resources/primeng.min.css' in styles.css.
So I set the code in '/src/styles.css' file like this,
```
<SandpackProvider 
      template='angular'
      files={{
       "/src/styles.css": `@import '/node_modules/primeng/resources/primeng.min.css';`
      }}
</SandpackProvider>
```

But this seems not work. Could you please provide some guidance about how to do this?
Thanks!

**Comment by danilowoz** [comment]
Hey! I think you're looking for the `externalResource` API: https://sandpack.codesandbox.io/docs/getting-started/custom-content#static-external-resources

Hope it helps

**Comment by WangJiaoJo** [comment]
@danilowoz Thanks for your reply. For loading external resources with URL link, it works fine. But how can I import the files from node_modules which does not have a URL link? Thanks.
