### ISSUE TITLE
HTML script not read

### ISSUE THREAD

**Issue by X-Ry** [codesandbox/sandpack#564]
# Bug report

## Packages affected

-   [x] sandpack-client
-   [ ] sandpack-react

## Description of the problem

I'm trying to use Sandpack Client to display html code, but it seems like the javascript in the script tags gets ignored. 
For example [in this code sandbox](https://codesandbox.io/s/adoring-stallman-kqvnpc?file=/App.svelte) I try to create a changeable header using Sandpack Client. It seems like the script tags in the HTML get ignored when displayed in the iframe, but when accessing the code from the "Open in CodeSandbox" button in its own Sandbox it works fine.

### Your Environment

| Software                | Name/Version |
| ----------------------- | ------------ |
| Sandpack-client version |        1.5.4      |
| Sandpack-react version  |              |
| Browser                 |             |
| Operating System        |          MacOS    |

**Comment by danilowoz** [comment]
Yeah, this's not trivial to fix. We've tried many times, and so far, we didn't make any progress.

I'd suggest keeping a look at https://github.com/codesandbox/sandpack/issues/44 and https://github.com/codesandbox/sandpack/issues/32 to track the progress of it
