### ISSUE TITLE
Documentation: https://sandpack.codesandbox.io/ website - sandbox icon not constrained to its container

### ISSUE THREAD

**Issue by mikestaas** [codesandbox/sandpack#568]
Chrome v105, macOS 12.5, Apple M1

On the https://sandpack.codesandbox.io/ website in the 2nd section "A live coding environment in minutes." the sandbox icon svg is rendered significantly larger than the icon container component, partially obscuring the text for the "Advanced preview" bullet point preceding it.

<img width="533" alt="image" src="https://user-images.githubusercontent.com/109115090/188242436-c5461878-d04b-405f-be5e-59854a1f72c8.png">

**Comment by danilowoz** [comment]
Ops, thanks for letting us know
