### ISSUE TITLE
Console: export 'useId' was not found in 'react' 

### ISSUE THREAD

**Issue by jodyheavener** [codesandbox/sandpack#575]
# Bug report

## Packages affected

-   [ ] sandpack-client
-   [x] sandpack-react

## Description of the problem

In development, usage of React < v18 results in noisy console logging because we are accessing `React.useId` when it doesn't exist.

<img width="648" alt="CleanShot 2022-09-15 at 16 44 18@2x" src="https://user-images.githubusercontent.com/6392049/190495205-0b4f51d8-034c-4988-b6a1-76a641b0ee63.png">

It's obfuscated, but I'm guessing it comes from this line: https://github.com/codesandbox/sandpack/blob/main/sandpack-react/src/components/CodeEditor/useGeneratedId.ts

Oddly enough, it's not actually being imported there, but the generated ESM converts it to that:

```
import{useId as rs,useRef as Vr}from"react";var ss=e=>typeof e=="string"?e:typeof rs=="function"?rs():Vr(ue()).current;
```

Not sure what the solution is... maybe replacing the line with something like `"useId" in React` would solve it? But I'm guessing it would still always convert to that import syntax.

### What steps can we take to reproduce the problem?

- Install `@codesandbox/sandpack-react` in a project with React 17.x
- Render one of the package components
- Open your developer console, observe output

### Your Environment

| Software                | Name/Version |
| ----------------------- | ------------ |
| Sandpack-react version  |      1.8.0        |

**Comment by danilowoz** [comment]
Yeah, you're right. By using `"useId" in React`, it will compile to:
```js
import * as ft from "react";
var rs = e => typeof e == "string" ? e : "useId" in ft && typeof ft.useId == "function" ? ft.useId() : ft.useRef(ue()).current
```

Which should avoid such warning
