### ISSUE TITLE
Documentation: Different templates for react and client?

### ISSUE THREAD

**Issue by zaini** [codesandbox/sandpack#583]
The templates for React: https://sandpack.codesandbox.io/docs/getting-started/custom-content#templates

The templates for Sandpack-Client: https://sandpack.codesandbox.io/docs/advanced-usage/client#sandboxinfo

As you see, they're different but similar. Is there a reason for this? Can we have an example of using the templates for Sandpack-Client?

I like the React ones because I have use the template to provide the majority of the boilerplate stuff and then just define a file like App.tsx to create the components that will be rendered in the preview. Can't seem to do the same thing with client.

**Comment by danilowoz** [comment]
Hey, actually, they are different things. I believe the naming is causing this confusion, and they should have been named differently.

- Sandpack-client "template", read environment instead: it tells which environment the given files/sandbox should run, for example, react or vue. Based on this information, the bundler will load and bundler the files properly.
- Sandpack-react template: a set of files and configuration (dependencies and entry point) that provides the minimal running project to the bundler.

All in all, Sandpack-react template needs to tell to the client which environment it should run, which wrongly is "template" as well.

Does it make sense?

**Comment by zaini** [comment]
Thanks. Are there plans to make the sandpack-react templates available for client? I quite like the default files/configs the templates provide.

**Comment by danilowoz** [comment]
Not really, the idea is to keep sandpack-client as simple as possible and leave the consumer to implement defaults and templates. I'd encourage you to continue mimicking the template from Sandpack react if it works for you.

Thanks
