### ISSUE TITLE
Exclude markdown from default languages

### ISSUE THREAD

**Issue by gaearon** [codesandbox/sandpack#588]
# Tell us how you think we can improve Sandpack

## Packages affected

-   [ ] sandpack-client
-   [x] sandpack-react

## What is this feature?

This seems unnecessary as a default:

https://github.com/codesandbox/sandpack/blob/a746ae3ae700bf3b64b8e14e5caee3cb57dd307d/sandpack-react/src/components/CodeEditor/utils.ts#L5

It's not very common that a code editor would need a Markdown example outside of a full sandbox environment.

## How would your idea work?

Let's exclude it by default, and let people add it as an extra lang as opt in.

**Comment by danilowoz** [comment]
Fair enough, Sandpack supports loading additional languages, and Markdown doesn't seem more necessary as a default language
