### ISSUE TITLE
Hacktoberfest: contribute to Sandpack Themes

### ISSUE THREAD

**Issue by danilowoz** [codesandbox/sandpack#596]
![image](https://user-images.githubusercontent.com/4838076/193264328-568b275e-0d91-43e5-ab61-2af2adb79e82.png)

We're open to supporting new Sandpack themes because our key goal is empowering developers to include custom live coding experiences over the web, regardless of your website layout or level of design expertise. That's why we provide plenty of options under `@codesandbox/sandpack-themes`, and we want to offer even more options. So, how can you contribute to new themes?

**Sandpack Theme Builder**

Sandpack provides a tool to guide you in creating your custom theme. Start with a dark or light theme, and then add your custom values like primary and secondary colors. 

Plus, if you want to give an even more personal touch, you can go to the Advanced tab and set colors for the syntax highlight and other cases.

[https://sandpack.codesandbox.io/theme](https://sandpack.codesandbox.io/theme)

**Publish a theme**

At this point, you need to go to the Sandpack repository, fork, and introduce some changes in your pull request. BTW, you can just use CodeSandbox Projects to do that:

1. Open the Sandpack repository on [CodeSandbox Projects](https://codesandbox.io/p/github/codesandbox/sandpack/main?file=%2FREADME.md);
2. Create a contribution branch, which will fork the repository for you:
    
<img width="211" alt="Screenshot 2022-09-27 at 09 31 22" src="https://user-images.githubusercontent.com/4838076/193258426-bf946c25-651c-4efc-9fb7-a7c6f6f8115b.png">
    
3. Create a new file in [codesandbox/sandpack/sandpack-themes/src](https://github.com/codesandbox/sandpack/tree/main/sandpack-themes/src) folder with following file `[theme name].ts`
4. The content of this file must be an export for an object that contains the theme:

```jsx
import type { SandpackTheme } from "./types";

export const THEME_NAME: SandpackTheme = {
  colors: {
		...
  },

  syntax: {
		...
  },
  font: {
    ...
  },
};
```

5. Include your new theme into the [`index.ts`](https://github.com/codesandbox/sandpack/blob/main/sandpack-themes/src/index.ts) file, that exposes all themes.

Still not clear? Feel free to contact us on Discord or on GitHub.

**Comment by VedanthB** [comment]
Hi I would like to give this a try.

**Comment by VedanthB** [comment]
Hi @danilowoz I have added a theme and created a PR , please review.

**Comment by Ananyamadhu08** [comment]
Hi can I also add another theme ?

**Comment by danilowoz** [comment]
Sure, @Ananyamadhu08! It's open for contributions

**Comment by VedanthB** [comment]
Hi @danilowoz  can I add more themes ?

**Comment by danilowoz** [comment]
Hey, sure! Let me know if you need any help 😄

**Comment by VedanthB** [comment]
Hey @danilowoz , I've added a dew themes please review. 😄

**Comment by Ananyamadhu08** [comment]
Hello @danilowoz, I have added some new themes as well please review. :)
