### ISSUE TITLE
replace node-sass by dart-sass in sandpack

### ISSUE THREAD

**Issue by danilowoz** [codesandbox/sandpack#614]
### Discussed in https://github.com/codesandbox/sandpack/discussions/613

<div type='discussions-op-text'>

<sup>Originally posted by **Chris-Kin** October  8, 2022</sup>
There's `node-sass`(which is [deprecated](https://sass-lang.com/blog/libsass-is-deprecated)) in yarn.lock, and it's required by `package-build-stats@7.3.6`. In `package-build-stats@7.3.11` node-sass has been removed. Maybe we should update package-build-stats to 7.3.11 or higher version?</div>

**Comment by danilowoz** [comment]
Hey @Chris-Kin, it looks doable. Would you like to give it a try and update it?

Thanks

**Comment by Chris-Kin** [comment]
> Hey @Chris-Kin, it looks doable. Would you like to give it a try and update it?
> 
> Thanks

I'll take a try~

**Comment by alameer5** [comment]
من المتوجب تحديث احصائات الحزمه وبنائها الى 7.3.13
