### ISSUE TITLE
Sandbox can not use normally in official website 

### ISSUE THREAD

**Issue by Undertone0809** [codesandbox/sandpack#637]
# Bug report

## Packages affected

-   [ ] sandpack-client
-   [ ] sandpack-react

## Description of the problem
The [official website](https://www.joshwcomeau.com/react/next-level-playground/) sandpack  components shows "Unable to establish connection with the sandpack bundler. Make sure you are online or try again later. If the problem persists, please report it via [email](mailto:hello@codesandbox.io?subject=Sandpack%20Timeout%20Error) or submit an issue on [GitHub.](https://github.com/codesandbox/sandpack/issues)" error is as follows. If it is bug of website or that's only my problem?
![image](https://user-images.githubusercontent.com/72488598/199763775-1026bbd3-b207-4fc0-9005-f3c172d7d934.png)

## What were you doing when the problem occurred?
I do nothing and just browse the website.

### What steps can we take to reproduce the problem?
You can open the website and have a see.

### Your Environment

| Software                | Name/Version |
| ----------------------- | ------------ |
| Sandpack-client version |              |
| Sandpack-react version  |              |
| Browser                 |              |
| Operating System        |              |

**Comment by danilowoz** [comment]
Hey, thanks for letting us know about this issue.

 Is it still happening for you? I just tested, and it seems it's back again. Unfortunately, it can happen for many reasons: network issues, third services are down, your connection is slow. 

<img width="865" alt="Screenshot 2022-11-04 at 09 23 01" src="https://user-images.githubusercontent.com/4838076/199938127-c6e4ee76-0c72-4e4e-ae98-dff0e1751a8a.png">

**Comment by Undertone0809** [comment]
> Hey, thanks for letting us know about this issue.
> 
>  Is it still happening for you? I just tested, and it seems it's back again. Unfortunately, it can happen for many reasons: network issues, third services are down, your connection is slow. 
> 
> <img width="865" alt="Screenshot 2022-11-04 at 09 23 01" src="https://user-images.githubusercontent.com/4838076/199938127-c6e4ee76-0c72-4e4e-ae98-dff0e1751a8a.png">
> 

I try again. It's because my connection slowly. Thanks for your replying.

**Comment by madou** [comment]
Hello I'm having this problem today - is there anything that can be done from my end to diagnose?

**Comment by Undertone0809** [comment]
I can not repeat your problem. As [danilowoz](https://github.com/danilowoz) say: 
> It can happen for many reasons: network issues, third services are down, your connection is slow.

**Comment by danilowoz** [comment]
CodeSandbox was down for a few minutes last night, this can explain why you all saw this message.

Let me know if it is still happening.

**Comment by donavon** [comment]
I'm seeing this right now on the Sandpack docs site https://sandpack.codesandbox.io/docs/getting-started/install

Comeau's site and the React beta docs both work fine for me. Is there an issue or is it just me?

<img width="1335" alt="image" src="https://user-images.githubusercontent.com/887639/215174593-4fba30ae-deff-4f55-9b8e-9098dca6df4a.png">

**Comment by donavon** [comment]
@danilowoz 

Curious. I'm having this issue on my localhost site as well. If I set `bundlerURL` to 1.3.2, it works. Weird as simply installing version 1.3.2 still tries loading 1.20.6

```tsx
<Sandpack
  theme="dark"
  template="react"
  options={{
    bundlerURL: 'https://1-3-2-sandpack.codesandbox.io/',
  }}
/>
```

**Comment by donavon** [comment]
It's seems to be working and I se it loading 1-20-7. thx!
