### ISSUE TITLE
Sandpack Client Cross-Origin Issue

### ISSUE THREAD

**Issue by illestrater** [codesandbox/sandpack#638]
# Bug report

## Packages affected

-   [ [✓](https://fsymbols.com/signs/tick/)] sandpack-client
-   [ ] sandpack-react

## Description of the problem
Getting an error `Refused to display 'https://1-12-1-sandpack.codesandbox.io/' in a frame because it set 'X-Frame-Options' to 'sameorigin'.`

## What were you doing when the problem occurred?
Developing using Sandpack normally, all of a sudden no access is available across multiple environments across the web

### What steps can we take to reproduce the problem?
Open a sandpack anywhere except from codesandbox.io

### Your Environment

| Software                | Name/Version |
| ----------------------- | ------------ |
| Sandpack-client version |              |
| Sandpack-react version  |              |
| Browser                 |              |
| Operating System        |              |

**Comment by madou** [comment]
This also seems to affect the wider csb environment, see: https://github.com/codesandbox/codesandbox-client/issues/7113

**Comment by tristandubbeld** [comment]
Hello, thanks for reporting this! Sorry for the inconvenience. It was a wider CSB issue but it should work again, can you confirm this?

**Comment by saurabhdaware** [comment]
It started working for me! Thanks for the quick response 👯

**Comment by illestrater** [comment]
> Hello, thanks for reporting this! Sorry for the inconvenience. It was a wider CSB issue but it should work again, can you confirm this?

Seems fixed, now will close thank you!
