### ISSUE TITLE
 to many  package request  when using private registry

### ISSUE THREAD

**Issue by cheapCoder** [codesandbox/sandpack#639]
# Bug report

## Packages affected

-   [ ] sandpack-client
-   [x] sandpack-react

## Description of the problem
I use private registry to load a dependency, but network show pretty much package request which cause slow render of preview.
the registry proxy I use is Verdaccio, the same to the docs example.
after requested the lib (the file is `xxx-1.0.30.tgz`), codesandbox starts to request the lib's dependency and send lots of `package.json` request.
I'm not sure that this situation occur is because the lib build isn't right or some Verdaccio proxy config lost.
I raise it here because the request initiator is codesandbox(the image show), sorry for the mistake if it's not proper to submit to sandpack
![image](https://user-images.githubusercontent.com/60960561/200255667-fd0dc448-c06e-42cf-a5f5-e68a03b466c2.png)

### Your Environment

| Software                | Name/Version |
| ----------------------- | ------------ |
| Sandpack-client version |              |
| Sandpack-react version  |      ^1.15.5        |
| Browser                 |         google chrome(107.0.5304.87)     |
| Operating System        |       macOS 13.0       |

**Comment by danilowoz** [comment]
Hey, would you mind sharing your Sandpack configuration (without any sensitive data)? Like the NPM registry configuration and sandbox package json

Thanks

**Comment by cheapCoder** [comment]
> 

thanks for your reponse, here is my configuration
```js
```

**Comment by cheapCoder** [comment]
> 

thanks for your reponse, here is my configuration
```js
 <Sandpack
        theme={atomDark}
        template="react-ts"
        customSetup={{
          dependencies: {
            '@registry/mydependency': 'xxx',
          },
          npmRegistries: [
            {
              enabledScopes: ['@registry'],
              limitToScopes: true,
              registryUrl: 'https://npm.xxx.site',
            },
          ],
        }}
        files={{
          '/App.tsx': code,
        }}
        options={{
          visibleFiles: [
            '/App.tsx',
            'tsconfig.json',
            '/index.tsx',
            '/styles.css',
            '/public/index.html',
            '/package.json',
          ],
          showRefreshButton: true,
          showTabs: true,
          closableTabs: true,
          showLineNumbers: true, // default - true
          showInlineErrors: true, // default - false
          // wrapContent: true, // default - false
          editorHeight: '100vh', // default - 300
          editorWidthPercentage: 50, // default - 50
        }}
      />
```

As for the parent components, I used `SandpackProvider` to wrap the sandpack component for the `useSandpack` api
```js
  <SandpackProvider
      options={{ bundlerURL: 'https://sandbox-bundler.netlify.app', skipEval: true }}
      template="react"
    >
      <Playground />
    </SandpackProvider>
```
there is one more question I didn't mention, the request still send from sandcodebox even though I config `bundlerURL`

**Comment by cheapCoder** [comment]
@danilowoz Also, the `xxx-1.0.30.tgz` tarball contains bundled resources
<img width="242" alt="image" src="https://user-images.githubusercontent.com/60960561/200448978-da73c0db-6c76-4df6-b865-d4a6e93eb20d.png">

but sandpack requests dependencies from `https://cdn.jsdelivr.net/npm` instead of using the `es` resource directly, 

the tarball package.json looks like this:
```json
  "sideEffects": [
    "dist/*",
    "es/**/style/*",
    "lib/**/style/*",
    "*.less"
  ],
  "main": "lib/index.js",
  "module": "es/index.js",
  "unpkg": "dist/sds.min.js",
  "typings": "lib/index.d.ts",
  "publishConfig": {
    "registry": "http://npm.xxx.site/"
  },
```

**Comment by cheapCoder** [comment]
@danilowoz Any update?  Is it possible that I need to configure `https` instead of `http` for the private packge?
```diff
  "publishConfig": {
-    "registry": "http://npm.xxx.site/"
+    "registry": "https://npm.xxx.site/"
  },
```
