### ISSUE TITLE
Feature request: Tailwind CSS support

### ISSUE THREAD

**Issue by rubytree33** [codesandbox/sandpack#640]
# Tell us how you think we can improve Sandpack

## Packages affected

-   [x] sandpack-client
-   [x] sandpack-react [if a change in API is required]

## What is this feature?

Add support for, or hooks for, adding [Tailwind CSS](tailwindcss.com/) to the sandbox. I use Tailwind with React regularly, but I couldn't find any way to make it work in Sandpack in the docs or the code.

## How would your idea work?

One way or another, it should be possible to allow the user to write JSX with Tailwind classes and have it compile correctly.

Ideally, you would be able to create a custom configuration with the relevant dependencies and provide the Tailwind and PostCSS configuration files in the `files` prop. Alternatively, there would be hooks to modify the build process so that this could be done like in a normal React app. See [here](https://tailwindcss.com/docs/guides/create-react-app) for an example of how this configuration usually works.

## Do you have any examples of how you would like to see us implement it?

I would be happy with a way to create a template using Tailwind similar to how the React template is defined internally ([here](https://github.com/codesandbox/sandpack/blob/5279a53bd7c34663730d5f1ead21c7949bb2742e/sandpack-react/src/templates/react.ts)) according to the configuration explained above.

Edit: usage example https://gist.github.com/rubytree33/1aac243a06a0b881934532c1f18e4077

**Comment by danilowoz** [comment]
Hey, you could consume Tailwind by CDN, like this example: https://codesandbox.io/s/tailwind-cdn-v75yjk?file=/src/App.js

I know it's far from a real case, but we're working on supporting such an elaborate setup.

**Comment by rubytree33** [comment]
This is great actually, thank you! I didn't realize using `externalResource` like this would actually work. I don't see anything in the documentation about it either.

I'll leave this issue open for doing this without relying on a CDN, but this workaround is good to know about.

**Comment by danilowoz** [comment]
I'm going to close it, because we already have it on our roadmap.

Thanks for asking it!

**Comment by JiangWeixian** [comment]
Is able to use tailwind plugins in sandpack?

**Comment by MurakamiKennzo** [comment]
any update about this?

**Comment by artivilla** [comment]
has anyone made this work?

**Comment by theshadowagent** [comment]
Any update here?

**Comment by aficus11** [comment]
That's crazy. It's 2026 and no Tailwind 4 support (with custom theme variables) without CDN. This project is abandoned?
