### ISSUE TITLE
Custom bundlerURL in sandpack-react

### ISSUE THREAD

**Issue by PhilipWee** [codesandbox/sandpack#649]
# Tell us how you think we can improve Sandpack

## Packages affected

-   [ ] sandpack-client
-   [x ] sandpack-react

## What is this feature?

Right now if you're not using the built in hooks you can use a custom bundler URL like this: 
```
new SandpackClient(iframe, sandboxInfo, {
  bundlerURL: "https://your-hosted-version",
});
```

But I can't seem to see the relevant option in when using SandpackProvider and useSandpack, either I'm missing something in the docs or something

An additional comment I have is that the bundler keeps being unable to load from the provided CDN (around like noon Singapore time), which is the only reason why I'm looking at hosting it myself, other than that it works great.

It always becomes unable to load for a while, then fixes itself magically

![image](https://user-images.githubusercontent.com/41712275/204960298-1c52788b-5a61-47dc-bebc-6643ede0ef32.png)

## How would your idea work?

Self explanatory I hope

## Do you have any examples of how you would like to see us implement it?

`<SandpackProvider template="react-ts" bundlerURL: "https://your-hosted-version">`

**Comment by PhilipWee** [comment]
Okay for anybody who comes in the future - I've found the option - it's as below:

```
<SandpackProvider
        template="react-ts"
        //TODO: Host our own bundler
        options={{
          bundlerURL="XXX"
        }}
      >
```

**Comment by danilowoz** [comment]
Hey @PhilipWee, glad you managed it!
How did you find it? How can we make this clearer in the documentation? 

Thanks
