### ISSUE TITLE
'Ref is not defined' when I use import type { Ref } from 'vue' in 'vue3 template'

### ISSUE THREAD

**Issue by UstinianMobius** [codesandbox/sandpack#662]
# Bug report

## Packages affected

sandpack-react

## Description of the problem

I'm not sure if this is a sandpack bug, 'Ref is not defined' when I use import type { Ref } from 'vue' in 'vue3 template' or other import type {xxxx} in 'xxx'

## What were you doing when the problem occurred?

Following the [sandpack "private packages" docs](https://sandpack.codesandbox.io/docs/guides/private-packages) registry setup as follows,  use 'vue3 template' and use custom welcome template

### Your Environment

| Software                | Name/Version |
| ----------------------- | ------------ |
| Sandpack-react version  |         ^1.18.0     |
| Browser                 |       Google Chrome 108.0.5359.71 (arm64)       |
| Operating System        |       macos Big Sur (Apple M1)       |

**Comment by danilowoz** [comment]
Hey! It seems you're trying to use Typescript types on a Vue template. So, you should you `vue3-ts`, which contains the Typescript configuration to consume types.
