### ISSUE TITLE
There was an error using the extension

### ISSUE THREAD

**Issue by KeyToLove** [codesandbox/sandpack#666]
# Bug report

## Packages affected

-   [ ] sandpack-client
-   [ ] sandpack-react

## Description of the problem
when i use Codemirror extensions in the CodeEditor component like this
```js
<Sandpack
  options={{
    codeEditor: {
      extensions: [autocompletion()],
      extensionsKeymap: [completionKeymap],
    },
  }}
  template="react"
/>
```
but console show me below errors , how can i fix up this problem :(
![image](https://user-images.githubusercontent.com/54970106/207568749-67ec4b83-6039-4bfa-9239-f3f5a4d2afb1.png)

## What were you doing when the problem occurred?

https://github.com/codesandbox/sandpack/pull/286#issue-1093281496

### Your Environment

| Software                | Name/Version |
| ----------------------- | ------------ |
| Sandpack-client version |              |
| Sandpack-react version  |              |
| Browser                 |              |
| Operating System        |              |

**Comment by danilowoz** [comment]
Would you mind providing a sandbox to reproduce this error? I'd like to check the dependencies versions

**Comment by KeyToLove** [comment]
> Would you mind providing a sandbox to reproduce this error? I'd like to check the dependencies versions


sorry i don't know how to use sandbox reproduce this problem

I would appreciate it if you would take the time to look at this minimal reproduce demo :))

https://github.com/KeyToLove/ant-design-vue-playground


The error was caused by these code
![image](https://user-images.githubusercontent.com/54970106/208406493-3d5fc437-daf9-4894-a789-76972455a63a.png)
