### ISSUE TITLE
Getting SandpackCodeEditor code on change

### ISSUE THREAD

**Issue by basketbla** [codesandbox/sandpack#676]
Is there a way to use this hook with the SandpackCodeEditor component rather than a different editor?

### Discussed in https://github.com/codesandbox/sandpack/discussions/314

<div type='discussions-op-text'>

<sup>Originally posted by **risenW** January 20, 2022</sup>
I want to listen to changes in the SandpackCodeEditor component and set the code to my own state. That is something like:

```javascript
import {
  useSandpack,
  SandpackProvider,
  SandpackLayout,
  SandpackCodeEditor
} from "@codesandbox/sandpack-react";
import { useState, useEffect } from 'react';


export default function Editor({ id }: { id: string }) {
  const [codeC, setCodeC] = useState('');

  const handleCurrentCodeStateUpdate = ({ id, code }: { id: string, code: string }) => {
    console.log("This is the code", code);
    setCodeC(code)
    //do something with the code, like set to global state
  }

  return (
    <div
      onKeyDown={handleKeyPress}
    >
      <SandpackProvider template="vanilla">
        <SandpackLayout>
          <SandpackCodeEditor
            onChange(handleCurrentCodeStateUpdate)  //something like an onChange event listener.

          />
        </SandpackLayout>
      </SandpackProvider>
    </div>
  );
}



```

I know I'm doing this wrong, is there a way to properly listen for code editor changes. I'm building a custom code compiler and just needs the editor. </div>

**Comment by ofergoli** [comment]
Any updates on that?
