### ISSUE TITLE
Sandpack preview's iframe is not setting allow with domain

### ISSUE THREAD

**Issue by Hensenh** [codesandbox/sandpack#686]
# Bug report

## Packages affected

-   [ ] sandpack-client
-   [X] sandpack-react

## Description of the problem
The iframe's allow is not setting a domain in the allow list. This is causing it to use the default behavior of only providing the listed permissions to domain matching the src on the iframe. It looks like Sandpack's iframe doesn't have a src attribute so this results in no permission being granted to the iframe.

## What were you doing when the problem occurred?
I saw that in #682 iframe permissions was added so I tried to use the latest release of Sandpack with code that attempts to access the microphone, camera, and screen sharing and it fails to ask the browser for permission. I was able to fix this by adding the bundlerUrl (https://1-20-1-sandpack.codesandbox.io/) after the permissions in the html and reloading the frame.

### What steps can we take to reproduce the problem?
Create a Sandpack preview with the vanilla template. 

`navigator.mediaDevices.getUserMedia({
  audio: true
})
`

### Your Environment

| Software                | Name/Version |
| ----------------------- | ------------ |
| Sandpack-client version |              |
| Sandpack-react version  | 1.20.4 |
| Browser                 |     Chrome 108.0.5359 |
| Operating System        |  macOs Monterey 12.3 |

**Comment by rakesh-snippyly** [comment]
Hi team, Checking in on this issue. We would really appreciate any inputs here. 🙏
