### ISSUE TITLE
Warning: React.Fragment can only have `key` and `children` props.  Possibly from SandpackConsole.tsx

### ISSUE THREAD

**Issue by rebeccapeltz** [codesandbox/sandpack#688]
# Bug report
I'm following instructions for setup and I see this warning in Chrome devtools
```
react.development.js:209 Warning: Invalid prop `className` supplied to `React.Fragment`. React.Fragment can only have `key` and `children` props.
    at Sandpack (http://localhost:3000/static/js/bundle.js:6271:20)
    at App
```
I saw there was a fix for Sandpack.tsx (https://github.com/codesandbox/sandpack/pull/601).  There is also a React.Fragment call in SandpackConsole.tsx that includes a className:

```
  <React.Fragment key={id}>
                {data.map((msg, msgIndex) => {
                  const fixReferences = references.slice(
                    logIndex,
                    references.length
                  );

                  return (
                    <div
                      key={`${id}-${msgIndex}`}
                      className={classNames(
                        consoleItemClassName({ variant: getType(method) })
                      )}
                    >
```

## Packages affected

-   [ ] sandpack-client
-   [ ] sandpack-react

## Description of the problem
Would like to resolve a React.Fragment warning
## What were you doing when the problem occurred?
working through the docs set up
### What steps can we take to reproduce the problem?
Maybe the fix for the Sandpack.tsx could be applied to SandpackConsole.tsx

You can reproduce this by working through the [setup instructions](https://sandpack.codesandbox.io/docs/getting-started/install).  You should see the warning in devtools with this starter code:

```
import { Sandpack } from "@codesandbox/sandpack-react";
export default function App() {
  return (
    <Sandpack 
      // You can change these examples!
      // Try uncommenting any of these lines
      // theme="dark"
      // template="react"
    />
  );
}
```

### Your Environment

| Software                | Name/Version |
| ----------------------- | ------------ |
| Sandpack-client version |           |
| Sandpack-react version  |      1.20.4           |
| Browser                 |   Chrome 109.0.5414.87           |
| Operating System        |     Mac Ventura 13.1         |

**Comment by danilowoz** [comment]
Thank you!
