### ISSUE TITLE
Add a new flag to <SandpackConsole> that clears messages on each re-render

### ISSUE THREAD

**Issue by iampava** [codesandbox/sandpack#692]
# Tell us how you think we can improve Sandpack

Add a flag to `<SandpackConsole>` that clears the console on each re-render.

## Packages affected

-   [ ] sandpack-client
-   [x] sandpack-react

## What is this feature?

Currently, while using the `<SandpackConsole>` logs keep being added. I think it should have a flag, similar to how browsers handle this using **Presever console**, which console when/how the messages are deleted.

**Comment by danilowoz** [comment]
https://github.com/codesandbox/sandpack/pull/743 implements it:

```js
<SandpackConsole resetOnPreviewRestart />
```

**Comment by iampava** [comment]
Amazing! Thanks 🙌
