### ISSUE TITLE
Sandpack Bundler is getting a 403 error

### ISSUE THREAD

**Issue by Hensenh** [codesandbox/sandpack#694]
# Bug report

## Packages affected

-   [ ] sandpack-client
-   [X] sandpack-react

## Description of the problem
I am seeing a 403 error with a response of "Package size exceeded the configured limit of 100 MB." from the new release of Sandpack.

## What were you doing when the problem occurred?
I updated Sandpack to the latest version and tried running it.
### What steps can we take to reproduce the problem?

Use the newest version of Sandpack and show the preview.

### Your Environment

| Software                | Name/Version |
| ----------------------- | ------------ |
| Sandpack-client version |              |
| Sandpack-react version  | 1.20.6 |
| Browser                 |109.0.5414.119  |
| Operating System        |Mac 12.3  |

**Comment by jerrywu001** [comment]
Same issue. It started at version `@codesandbox/sandpack-react@1.20.6`.

#693

**Comment by rebeccapeltz** [comment]
Same issue. Seeing it in 1.20.6. 
https://github.com/rebeccapeltz/cld-training-react
https://taupe-douhua-b33b55.netlify.app/
<img width="1424" alt="source-code-analyze" src="https://user-images.githubusercontent.com/354444/215365947-c81005ab-64d9-48d5-8ad0-96bf2307ee12.png">

I ran source code analyzer and it looks like I'm under 100 MB.

**Comment by danilowoz** [comment]
Thanks for letting us know. We recently pushed a fix, which should fix it! 
Please update to the latest Sandpack version
