### ISSUE TITLE
Can i rename App.js in Sandpack?

### ISSUE THREAD

**Issue by wjjhhh** [codesandbox/sandpack#699]
# Tell us how you think we can improve Sandpack

## Packages affected

-   [ ] sandpack-client
-   [ ✔] sandpack-react

## What is this feature?
I want to use ‘index.js’ resplace ‘App.js‘

**Comment by danilowoz** [comment]
Hey, you cannot exactly rename, but Sandpack allows you to pass custom files, which would make it possible to overwrite some files: 

```jsx
// pseudo-code
<Sandpack 
  files={{
   "/entry.js": `import App from "./index.js"
// rest
`,
   "/index.js": `
export default App = () => {}
`
  }}
/>

```

**Comment by wjjhhh** [comment]
> 

ok,thanks a lot

**Comment by wjjhhh** [comment]
> Hey, you cannot exactly rename, but Sandpack allows you to pass custom files, which would make it possible to overwrite some files:
> 
> ```js
> // pseudo-code
> <Sandpack 
>   files={{
>    "/entry.js": `import App from "./index.js"
> // rest
> `,
>    "/index.js": `
> export default App = () => {}
> `
>   }}
> />
> ```



> Hey, you cannot exactly rename, but Sandpack allows you to pass custom files, which would make it possible to overwrite some files:
> 
> ```js
> // pseudo-code
> <Sandpack 
>   files={{
>    "/entry.js": `import App from "./index.js"
> // rest
> `,
>    "/index.js": `
> export default App = () => {}
> `
>   }}
> />
> ```

ok,thanks a lot
