### ISSUE TITLE
Sandpack bundler connection issue

### ISSUE THREAD

**Issue by kickvicky** [codesandbox/sandpack#703]
# Bug report

## Packages affected

-   [ ] sandpack-bundler

### Your Environment

| Software                | Name/Version |
| ----------------------- | ------------ |
| Sandpack-client version |              |
| Sandpack-react version  |              |
| Browser                 |              |
| Operating System        |              |

**Comment by danilowoz** [comment]
Hey, could you please provide more information about this issue? Is there any link to reproduce this error or any other information?

**Comment by andreifloricel** [comment]
@danilowoz It's possible that it was a hiccup due to some UNPKG issues, see https://github.com/codesandbox/sandpack/discussions/706
It would be nice to be able to detect such issues in order to handle them gracefully.
