### ISSUE TITLE
Listener is missing to register/emit events in some cases.

### ISSUE THREAD

**Issue by JayaKrishnaNamburu** [codesandbox/sandpack#71]
It was quite tricky to point down exactly when it's happening. But at times, the `listener` from `useSandpack` is failing to listen for events emitted by the sandpack bundler.
https://codesandbox.io/s/eloquent-mccarthy-qr09r?file=/src/App.tsx

STR
- Open the console and we should be able to see the logs.
- Refresh the browser or `csb` preview. And in some instances the listener won't log the events.

https://user-images.githubusercontent.com/11075561/123729554-c96bde00-d8b2-11eb-8301-8de480e06884.mov

**Comment by JayaKrishnaNamburu** [comment]
And i get this error screen for registering listener, sometimes even when not trying to listen for one. Let me know, if i can help in some way to solve both the issues 😄 

![Screenshot 2021-06-29 at 10 04 46 AM](https://user-images.githubusercontent.com/11075561/123737948-85340a00-d8c1-11eb-988e-c2697eac63c2.png)

**Comment by alexnm** [comment]
Thanks for the report, we'll look into it! I also noticed an issue with hot module reload, some listners are not setup properly in the provider

**Comment by nkovacic** [comment]
Got the same issue when trying to register multiple Preview windows.

**Comment by alexnm** [comment]
I also found a scenario in which the listeners give an error. Will have to debug this inside the context.

https://codesandbox.io/s/jolly-poincare-zjoxf?file=/src/App.tsx (any change that triggers a hot reload throws an error)
