### ISSUE TITLE
Feature request to customize the tab menu

### ISSUE THREAD

**Issue by danilowoz** [codesandbox/sandpack#710]
## Description

<img width="801" alt="image" src="https://user-images.githubusercontent.com/27342882/216750722-ea179272-40f2-4155-b515-b57166cbddb0.png">

My requirement is to add delete button and add button.

[Link](https://sandpack.codesandbox.io/docs/getting-started/custom-ui#tabs)

I have confirmed that the delete function is available through the options in the link above.

But fundamentally, it would be more useful if the user could customize the tab part!

For example, I think the API for that feature request could look something like the one below!

```js
import {
  SandpackProvider,
  SandpackLayout,
  SandpackCodeEditor,
  SandpackPreview,
  // example
  SandpackTab,
  SandpackTabItem
} from "@codesandbox/sandpack-react";

// example
const files = {
  'App.js': 'code1',
  'Example.js': 'code2',
};

const delete = () => {
  alert('Delete');
}

const CustomSandpack = () => (
  <SandpackProvider template="react">
    <SandpackLayout>
      <SandpackCodeEditor>
        <SandpackTab>
          {Object.entries(files).map(([name, code]) => {
            return (
              <SandpackTabItem>
                <span>{name}</span>
                <button onClick={delete}>Delete</button>
              </SandpackTabItem>
            )
          })}
        </SandpackTab>
      </SandpackCodeEditor>
      <SandpackPreview />
    </SandpackLayout>
  </SandpackProvider>
);
```

Just an example, if there is a better structure or way, anything is welcome!

If you agree with the need for this feature, please comment!

**Comment by ryuhangyeong** [comment]
+1

**Comment by derek-cove** [comment]
+1 for new tab functionality - @danilowoz - you marked this as completed. How is it implemented?
