### ISSUE TITLE
React DevTools component is not available

### ISSUE THREAD

**Issue by yyildiz** [codesandbox/sandpack#712]
# Bug report

## Packages affected

-   [ ] sandpack-client
-   [x] sandpack-react

## Description of the problem
The ReactDevTools component is not available in the SandpackReact package anymore.
It's broken on the documentation page as well: https://sandpack.codesandbox.io/docs/advanced-usage/components#reactdevtools
![image](https://user-images.githubusercontent.com/10237552/217883134-141ff589-e6e9-4150-b910-198f822a4958.png)

### Your Environment

| Software                | Name/Version |
| ----------------------- | ------------ |
| Sandpack-client version |              |
| Sandpack-react version  |              |
| Browser                 |              |
| Operating System        |              |

**Comment by danilowoz** [comment]
We're considering dropping support for ReactDevTools, because Sandpack must be a more agnostic library instead a framework-driven library (although it's written on React). Please, feel free to open it anytime for further discussion

Thanks.
