### ISSUE TITLE
Next13 + storybook, loosing style at codeeditor

### ISSUE THREAD

**Issue by vcctm** [codesandbox/sandpack#715]
# Bug report

## Packages affected

-   [ ] sandpack-client
-   [ x] sandpack-react

## Description of the problem
CodeEditor Losing the style after the first render.

## What were you doing when the problem occurred?
Any theme that I try to apply seems to work in the first render but right after an instant, the code editor loses the style.

### What steps can we take to reproduce the problem?
I'm using Next13 (don't pretty sure if have support)
Trying to run in a storybook, directly but with vanilla, extract support can be vanilla?

https://user-images.githubusercontent.com/75961352/219219655-5f87077b-e732-40df-9781-07ed6e574629.mov

### Your Environment
Next13

| Software                | Name/Version |
| ----------------------- | ------------ |
| Sandpack-client version |              |
| Sandpack-react version  |  ^1.20.9 |
| Browser                 |     Chrome         |
| Operating System        |       MacOS       |

**Comment by vcctm** [comment]
By the way I add a new snapvideo with more lazy cpu for you guys can see what is happening:


https://user-images.githubusercontent.com/75961352/219227988-de4a6054-2d09-48bf-a2db-b103adbb3685.mov

**Comment by danilowoz** [comment]
Hey, @vcctm. Sorry for the late answer, but could you provide a sandbox where I can reproduce this error? BTW, are you using React Server Components, or is it a regular Next.js application?

**Comment by danilowoz** [comment]
Can you confirm if this still happens using the new Next.js SSR guide? https://sandpack.codesandbox.io/docs/guides/ssr#nextjs-app-dir
