### ISSUE TITLE
Something wrong with package exports

### ISSUE THREAD

**Issue by nicksrandall** [codesandbox/sandpack#724]
# Bug report

## Packages affected

-   [x] sandpack-client
-   [x] sandpack-react

## Description of the problem
Error from esbuild

```txt
✘ [ERROR] Could not resolve "@codesandbox/sandpack-client"

    ../../node_modules/.pnpm/@codesandbox+sandpack-react@2.0.6_biqbaboplfbrettd7655fr4n2y/node_modules/@codesandbox/sandpack-react/dist/esm/index.js:7:95:
      7 │ ...kClient, extractErrorDetails } from '@codesandbox/sandpack-client';
        ╵                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  Importing the directory "./dist" is forbidden by this package:

    ../../node_modules/.pnpm/@codesandbox+sandpack-react@2.0.6_biqbaboplfbrettd7655fr4n2y/node_modules/@codesandbox/sandpack-client/package.json:21:16:
      21 │       "import": "./dist",
         ╵                 ~~~~~~~~

  The presence of "exports" here makes importing a directory forbidden:

    ../../node_modules/.pnpm/@codesandbox+sandpack-react@2.0.6_biqbaboplfbrettd7655fr4n2y/node_modules/@codesandbox/sandpack-client/package.json:15:2:
      15 │   "exports": {
         ╵   ~~~~~~~~~


```

## What were you doing when the problem occurred?
Trying to build an app using esbuild.

### Your Environment

| Software                | Name/Version |
| ----------------------- | ------------ |
| Sandpack-client version |              |
| Sandpack-react version  |     2.0.6         |
| Browser                 |              |
| Operating System        |              |

**Comment by danilowoz** [comment]
ohhhh exports...

@DeMoorJasper does it make sense for you? I'm not an expert on exports

**Comment by azu** [comment]
I noticed that https://github.com/codesandbox/sandpack/blob/affdbd538ab3c6aab7cac53362747bcc674d5cd3/sandpack-client/package.json#L16-L18 refer same `.js` in import/require.

Maybe

```diff
    "./clients/node": {
-     "import": "./dist/clients/node/index.js",
+     "import": "./dist/clients/node/index.mjs",
      "require": "./dist/clients/node/index.js"
```

FYI: publint will be helpful
https://publint.dev/@codesandbox/sandpack-client@2.0.7
