### ISSUE TITLE
The reset of useSandpackConsole does not work

### ISSUE THREAD

**Issue by wyy0512** [codesandbox/sandpack#730]
# Bug report

## Packages affected

-   [ ] sandpack-client
-   [x] sandpack-react

## What were you doing when the problem occurred?
I have a custom CleanIcon requirement for console, and when I used reset of useSandpackConsole to clear the log, nothing happened.

### What steps can we take to reproduce the problem?
CleanIcon looks like this：
```
const CleanIcon = () => {
  const { reset } = useSandpackConsole();
  <div onClick={reset} >Clean</div>
}
```
Here's how I use it
```
<SandpackProvider template="react" files={files}>
  <CleanIcon />
  <SandpackCodeEditor />
  <SandpackPreview />
  <SandpackConsole />
</SandpackProvider>
```

### Your Environment

| Software                | Name/Version |
| ----------------------- | ------------ |
| Sandpack-client version |              |
| Sandpack-react version  |     2.0.1         |
| Browser                 |              |
| Operating System        |              |

**Comment by danilowoz** [comment]
Hey, @wyy0512! 

Actually, `useSandpackConsole` is working correctly. Each `CleanIcon` and `SandpackConsole` contain its own console context, and when you try to reset the consoles from `CleanIcon` it won't trigger the same action on other's context. Does it make sense? 

So, I can see two options here to manage your issue:
1. You could build your own Console component and render the console.logs, which would give you full control of resetting it;
2. `SandpackConsole` implements a new API to clean the logs imperatively by `React.ref`, which would looks something like this:

```js
// proposal solution, not implement yet
const consoleRef = useRef();

const onCleanConsole = () => {
  consoleRef.current?.reset();
}

return <SandpackConsole ref={consoleRef} />
```

**Comment by wyy0512** [comment]
@danilowoz 
Thank you very much for taking the time to answer my questions. The second solution looks great and fits my needs better, and I'm looking forward to the new api for SandpackConsole
