### ISSUE TITLE
Documentation: Is Sandpack still open source after nodebox integration?

### ISSUE THREAD

**Issue by Muhammad-Ahmad-Rai** [codesandbox/sandpack#732]
I just noticed that nodebox is closed-source, meaning it cannot be used for commercial purposes. However, sandpack-client has nodebox listed in its dependencies. Does this mean that sandpack can no longer be used for commercial purposes? Is there a change to sandpack license?
![image](https://user-images.githubusercontent.com/111280841/220034502-0f4a1f30-37b8-481d-ae99-d35323f90e59.png)

**Comment by danilowoz** [comment]
Hey, thanks for opening this issue.

So, you can find more details about the license on the Sandpack documentation: https://sandpack.codesandbox.io/docs/resources/faq#what-license-do-sandpack-and-nodebox-use

Happy to answer any other question
