### ISSUE TITLE
Add Vite + React + TS template

### ISSUE THREAD

**Issue by jakeboone02** [codesandbox/sandpack#744]
## Packages affected

Not sure...guessing `sandpack-client` only?

- [x] sandpack-client
- [ ] sandpack-react

## What is this feature?

New template exactly like `vite-react`, but using TypeScript (presumably named `vite-react-ts`).

## How would your idea work?

Same basic code as existing `vite-react` template, but fully TypeScript.

## Do you have any examples of how you would like to see us implement it?

The official "React (Vite + TS)" template on https://codesandbox.io would be a good starting point.

**Comment by jerrywu001** [comment]
@danilowoz ready to merge.

**Comment by jerrywu001** [comment]
@danilowoz ready to merge.
