### ISSUE TITLE
👀  Hiding Sandpack Tests

### ISSUE THREAD

**Issue by ubeytd** [codesandbox/sandpack#768]
# Tell us how you think we can improve Sandpack

## Providing Context and Use Case

At our school, we want to incorporate coding challenges into our platform to assess our students' coding abilities. 

We plan on using sandpack-react to achieve this goal. However, we want to ensure that our students are not just memorizing solutions, but are truly able to think and problem-solve. Therefore, we would like to hide the tests completely from view.

## Hidden Test Files

In verbose mode, when a test file fails, a link is displayed to show where the test file failed. However, if the test file is meant to be hidden, it would be great to address this behavior.

## Optional Props to Hide Verbose and Watch Buttons

In order to manually run tests with `dispatch({type:'refresh'})` and hide test file content in the Test component, we suggest adding `showVerbose` and `showWatch` props to the Test component. 🤗

## Packages affected

-   [ ] sandpack-client
-   [x] sandpack-react

**Comment by danilowoz** [comment]
Hey @ubeytd, that would be great! I'm really happy to know you're considering Sandpack in your coding challenges.

I have added your feature request to our internal backlog which we use to prioritize what to build next. We can't make any promises about the timing, but it's on the list! If you'd like to work on this feature with us, please create a pull request and we'll help you along the way.

**Comment by ubeytd** [comment]
Awesome! [Created PR](https://github.com/codesandbox/sandpack/pull/775) 🤗
