### ISSUE TITLE
Sandpack is erroring with "maximun callstack exceeded" presumably because of the files are now being marked as changed all the time?

### ISSUE THREAD

**Issue by nicksrandall** [codesandbox/sandpack#772]
@danilowoz Thanks for working on file change issues. While the changes you made did technically fix that issue, I think  it has caused another one where now my sandpack is erroring with "maximun callstack exceeded" presumably because of the files are now being marked as changed all the time?
<img width="361" alt="Screenshot 2023-02-24 at 3 14 52 PM" src="https://user-images.githubusercontent.com/1800460/221303674-db5ac0b9-6b18-4dd1-bae4-4f522dcade47.png">

_Originally posted by @nicksrandall in https://github.com/codesandbox/sandpack/issues/733#issuecomment-1444589819_

**Comment by danilowoz** [comment]
Hey, could you please provide a sandbox to reproduce it? I couldn't really see this error
