### ISSUE TITLE
On initial mount console.log is executed two times in `@codesandbox/sandpack-react`

### ISSUE THREAD

**Issue by VladSez** [codesandbox/sandpack#784]
Hello! Thank you for the awesome library

Not sure if this is a bug, but on initial mount `console.log` is executed two times (check logs at bottom right):

> sometimes `console.log` is executed only once but most of the time it's executed twice

![image](https://user-images.githubusercontent.com/16666234/220343812-7b16d80d-3820-41fb-8e68-efc97e7b54c2.png)

Reproduction:
https://codesandbox.io/s/sweet-roentgen-v2kdl6?file=/src/App.js

Is it expected? Can I make it to execute only one time on mount?

_Originally posted by @VladSez in https://github.com/codesandbox/sandpack/discussions/748_

**Comment by paul-berthelot** [comment]
Hey!
I think this is not a bug but only the way React works now.
You can check this blog, it explains why:
https://mariosfakiolas.com/blog/my-react-components-render-twice-and-drive-me-crazy/

**Comment by danilowoz** [comment]
It has been fixed recently

Thanks for reporting it
