### ISSUE TITLE
Ability to pass in locally sourced relative components

### ISSUE THREAD

**Issue by colbyfayock** [codesandbox/sandpack#793]
# Tell us how you think we can improve Sandpack

## Packages affected

-   [ ] sandpack-client
-   [x] sandpack-react

## What is this feature?

I was attempting to add Sandpack to the docs of one of my projects: https://github.com/colbyfayock/next-cloudinary

It's currently a yarn workspace project where in my docs, I use relative imports to grab the latest version of the modules:

```
import nextCloudinary from '../../../../next-cloudinary';
```

I was hoping to be able to somehow apply this to my Sandpack usage but couldn't figure out anything that "just worked"

Tried playing around with this local option, but I couldn't quite figure it out: https://sandpack.codesandbox.io/docs/resources/faq#how-to-load-local-dependencies

## How would your idea work?

Perhaps there could be a way to pass in a module as a dependency? For instance, maybe something along the lines of:

```
customSetup={{
  dependencies: {
    'next-cloudinary': nextCloudinary
  }
}}
```

That is if I couldn't use a relative location such as:

```
customSetup={{
  dependencies: {
    'next-cloudinary': '../../../../next-cloudinary'
  }
}}
```

**Comment by danilowoz** [comment]
Hey, I think I found a way to make it easier to load a local package and its dependency. To be very honest, @davincho found it! I'm going to leave here a preview and repository to reproduce it, but I promise to come back and create a detailed description, steps, and what are challenges to accomplish it. 

Hope it works for you

Preview: https://codesandbox.io/p/github/danilowoz/sandpack-local-dependencies/main?file=%2FREADME.md
Repo: https://github.com/danilowoz/sandpack-local-dependencies

**Comment by colbyfayock** [comment]
it seems to work!

https://next-cloudinary-l7ni6lvnm-colbyfayock.vercel.app/components/cldimage/basic-usage

relevant code: https://github.com/colbyfayock/next-cloudinary/pull/150

I think my only concern would be the amount of additional JS this might ship on top of the original since its basically doubling it (i would expect) but not sure if theres a better option

thanks for setting up the example

**Comment by danilowoz** [comment]
AMAZING! Really glad you made it!
