### ISSUE TITLE
Bad user experience when Vite-React and React are used together!!

### ISSUE THREAD

**Issue by jerrywu001** [codesandbox/sandpack#802]
# Bug report

## Packages affected

-   [ ] sandpack-client
-   [x] sandpack-react

## Description of the problem

The user experience is not good when Vite-React and React are used together.

chrome

```jsx
<Sandpack template="react" />

<Sandpack template="vite-react" />
```

**No logs display, and there is a long blank display until the result is successful.**

https://user-images.githubusercontent.com/12525415/223014095-be07e4ad-6e55-4420-b041-4db13ab3643f.mp4

**Comment by danilowoz** [comment]
Hey, can you provide a sandbox to reproduce it? I tried to run both `react` and `vite-react`, an they worked as expected: https://codesandbox.io/p/sandbox/sandpack-2-0-forked-czs9el?file=%2Fsrc%2FApp.tsx

**Comment by jerrywu001** [comment]
> Hey, can you provide a sandbox to reproduce it? I tried to run both `react` and `vite-react`, and they worked as expected: https://codesandbox.io/p/sandbox/sandpack-2-0-forked-czs9el?file=%2Fsrc%2FApp.tsx

online demo
https://stackblitz.com/edit/vitejs-vite-vxfg4g?file=src%2FApp.tsx

<img width="634" alt="image" src="https://user-images.githubusercontent.com/12525415/223298751-a64af902-b5d3-427b-80e8-1bd365f23930.png">

**Copy the preview URL of stackblitz, and open it in a new tab.**

**Comment by jerrywu001** [comment]
I can reproduce it 100% in the first time.

**Comment by jerrywu001** [comment]
Actually, it has nothing to do with webcontainers

https://user-images.githubusercontent.com/12525415/223404623-b6a4676b-e307-4262-ac03-2006a3619b26.mov

https://codesandbox.io/p/sandbox/adoring-artem-8rp80s?file=%2Fpackage.json

**Comment by jerrywu001** [comment]
work with latest version
