### ISSUE TITLE
Documentation: Unable to establish connection with the sandpack bundler

### ISSUE THREAD

**Issue by Aeolos71** [codesandbox/sandpack#807]
Unable to establish connection with the sandpack bundler. Make sure you are online or try again later. If the problem persists, please report it via [email](mailto:hello@codesandbox.io?subject=Sandpack%20Timeout%20Error) or submit an issue on [GitHub.](https://github.com/codesandbox/sandpack/issues)

I got the same message on all browsers please

**Comment by mohdashraf010897** [comment]
@Aeolos71 I got the same error. 

![image](https://user-images.githubusercontent.com/57627350/223694317-11c71ad0-83c4-4e70-9b82-5463214f6038.png)

**Comment by mohdashraf010897** [comment]
@Aeolos71 trying setting the `bundlerTimeOut` to a greater value

> 		<SandpackProvider
> 			options={{
> 				bundlerTimeOut: 120_000, // try using this
> 			}}
> 			
> 		>
> 			<SandpackPreviewContainer />
> 		</SandpackProvider>
