### ISSUE TITLE
SandpackTests: extend RunButton

### ISSUE THREAD

**Issue by danilowoz** [codesandbox/sandpack#821]
### Discussed in https://github.com/codesandbox/sandpack/discussions/820

<div type='discussions-op-text'>

<sup>Originally posted by **pratikgcet** March  7, 2023</sup>
Looking for a way to create a Run Button for running the test. The default button is really small and invisible.
I need to have a button in "verbose" mode</div>

**Comment by danilowoz** [comment]
Hey, @pratikgcet. I'd like to confirm that you would like to make this button more accessible or use it on a different place, right?  

![Screenshot 2023-03-08 at 13 14 30](https://user-images.githubusercontent.com/4838076/223722569-4e8b7028-9475-48da-b913-a76a3e520492.png)

**Comment by pratikgcet** [comment]
Hey @danilowoz 
Yes, ideally I would like to have both of them. The ideal scenario would be you can hide or unhide the default button which you have highlighted(I guess this wouldn't work when the method is "verbose") and have access to run test functionality from a custom button created using actionOnChildren? This way this Button can then maybe stay as it is and developers can make their own button? 
What's your view?

**Comment by pratikgcet** [comment]
hey @danilowoz - Any luck here please? I am kind of stuck because of this.

**Comment by pratikgcet** [comment]
I think we can cancel this one. We already have the dispatch method, so I can easily create a button and call the dispatch
like dispatch({type:'run-all-tests'});
