### ISSUE TITLE
getSandpackCssText breaks preview and logs

### ISSUE THREAD

**Issue by jeetiss** [codesandbox/sandpack#824]
# Bug report

## Packages affected

-   [ ] sandpack-client
-   [x] sandpack-react

## Description of the problem

`getSandpackCssText` injects wrong CSS that breaks the preview and console output

### What steps can we take to reproduce the problem?

- follow the [ssr guide from the docs](https://sandpack.codesandbox.io/docs/guides/ssr)
- preview before

<img width="705" alt="Снимок экрана 2023-03-09 в 13 46 09" src="https://user-images.githubusercontent.com/6726016/224002907-22896708-876d-4856-aa6a-c6f55a9c7d07.png">

- preview after

<img width="706" alt="Снимок экрана 2023-03-09 в 13 46 35" src="https://user-images.githubusercontent.com/6726016/224002990-582ef945-2b16-4e8f-a7bb-fde35e3d9f9b.png">

### Your Environment

| Software                | Name/Version |
| ----------------------- | ------------ |
| Sandpack-client version |      latest  |

**Comment by jeetiss** [comment]
`getSandpackCssText` doesn't work as expected, it injects styles but they don't work

to reproduce:

- goto https://react-pdf-experiments-git-sandpack-jeetiss.vercel.app/sandpack
- disable js and reload the page
- check that styles are in but are not applied

<img width="1312" alt="Снимок экрана 2023-03-09 в 14 18 20" src="https://user-images.githubusercontent.com/6726016/224008651-67af779e-a4b4-425b-9bb8-29c216312bb3.png">

**Comment by danilowoz** [comment]
humm interesting, could you please provide the source code? I'd like to have a way reproduce this error on my own

**Comment by jeetiss** [comment]
sure, https://github.com/jeetiss/react-pdf-repl/pull/9
