### ISSUE TITLE
Support for life cycle scripts in package.json

### ISSUE THREAD

**Issue by similonap** [codesandbox/sandpack#827]
# Tell us how you think we can improve Sandpack

## Packages affected

-   [*] sandpack-client
-   [ ] sandpack-react

## What is this feature?

Currently only dev and start scripts are supported in package.json. It would be useful to support postinstall/prestart scripts also, so we can do some additional steps like running a transpiling step for typescript.

**Comment by danilowoz** [comment]
Maybe related to https://github.com/codesandbox/sandpack/issues/819

**Comment by danilowoz** [comment]
Closing in favor of https://github.com/codesandbox/sandpack/issues/819
