### ISSUE TITLE
Couldn't connect to server when using antd

### ISSUE THREAD

**Issue by fssh** [codesandbox/sandpack#845]
# Bug report

## Packages affected

-   [ ] sandpack-client
-   [ ] sandpack-react

## Description of the problem
When I import antd5, it shows me the error.

## What were you doing when the problem occurred?
Waiting for sandpack to render

### What steps can we take to reproduce the problem?
add antd dependency
![image](https://user-images.githubusercontent.com/18034841/225839225-49e6d181-9725-4c74-9790-60462d5c3473.png)
![image](https://user-images.githubusercontent.com/18034841/225838655-d87197d0-a230-4d22-ac84-dbba349f9391.png)

### Your Environment

| Software                | Name/Version |
| ----------------------- | ------------ |
| Sandpack-client version |              |
| Sandpack-react version  |    2.1.8          |
| Browser                 |             chrome |
| Operating System        |        win10      |

**Comment by DeMoorJasper** [comment]
Could you create a sandbox where we can reproduce this?

**Comment by fssh** [comment]
Sorry for waiting so long. I have tried many times. This could happen when I use "PageContainer" tag  of "@ant-design/pro-components". This only happened in sandpack, sandbox would be ok.
[https://codesandbox.io/s/cceu69?file=/App.js:156-239&utm_medium=sandpack](https://codesandbox.io/s/cceu69?file=/App.js:156-239&utm_medium=sandpack)

**Comment by DeMoorJasper** [comment]
Can't really tell what's wrong from the provided sandbox but probably it just times out because it's a big library?

**Comment by fssh** [comment]
> I agree that this must be a timeout due to the dependencies' size. You can increase the bundler timeout, like I did on this sandbox: https://codesandbox.io/p/sandbox/flamboyant-bardeen-exs2r6
> 
> Here's evidence that it works using the same file you provided on the sandbox above. <img alt="Screenshot 2023-04-03 at 10 34 24" width="832" src="https://user-images.githubusercontent.com/4838076/229525529-b7b2cf55-33d5-4b2c-8e41-c0e64d7348ae.png">

It works after setting bundlerTimeout. Thank you very much.
