### ISSUE TITLE
Sandpack is removing my CSS variables

### ISSUE THREAD

**Issue by anubra266** [codesandbox/sandpack#848]
# Bug report

## Packages affected

-   [ ] sandpack-client
-   [x] sandpack-react

## Description of the problem

I use remix run, and I have css variables from a css framework that uses, css layers and all.
Plugging in sandpack just gets rid of most of those variables, so I only see the ones from sandpack

**Comment by danilowoz** [comment]
Hey, could you please provide a reproducible example? I'm curious to know how Sandpack is affecting the global styles
