### ISSUE TITLE
Infinite loading if we just add the <SandpackPreview> inside <SandpackProvider>

### ISSUE THREAD

**Issue by iampava** [codesandbox/sandpack#851]
# Bug report

## Packages affected

-   [ ] sandpack-client
-   [x] sandpack-react

## Description of the problem
It seems like the following setup results (most of the time) in infinite loading, without ever showing the result/preview:

```jsx
<SandpackProvider template="vanilla-ts">
  <SandpackPreview />
</SandpackProvider>
```

On the other hand, if I wrap the `<SandpackPreview` inside a `<SandpackLayout>` it seems to be working:

```jsx
<SandpackProvider template="vanilla-ts">
  <SandpackLayout>
    <SandpackPreview />
  </SandpackLayout>
</SandpackProvider>
```

https://user-images.githubusercontent.com/11327761/226484234-0fa26d34-2eb2-4271-b060-c2be4fa67932.mov

### Your Environment

| Software                | Name/Version |
| ----------------------- | ------------ |
| Sandpack-client version |2.1.9|
| Sandpack-react version  |2.1.9|
| Browser                 |Firefox | Chrome|
| Operating System        |Mac OS Ventura|

**Comment by iampava** [comment]
Btw, I'm happy to contribute to this. Will find some time tomorrow, but if you can give me some pointers would be great 🙌

**Comment by iampava** [comment]
I found some time today to look into it. I tracked it into the `<LoadingOverlay>` component that doesn't detect that the Sandbox has loaded, so it overlays on top of the `<Preview>` forever.

Digging a bit further, I can see that the if I don't put the `<SandpackLayout>` this event never fires, that leads to the loading spinner never disapearing. But the preview underneath is actually visible.

https://github.com/codesandbox/sandpack/blob/1bc6276173066189ccf83bf7cc251dc0d302a6fa/sandpack-react/src/hooks/useLoadingOverlayState.ts#L30

I still don't know the cause, will have to dig deeper into that...

---

Offtopic: is there a way to easily run these components, for development I mean. I saw the Storybook, it's really helpful but since Storybook adds an iframe around the component I couldn't replicate the bug. So what I ended up doing was to use the components in the landing package, but their code doesn't update if I modify the react package, so I have to rebuild it again and again to test with my modifications.

**Comment by DeMoorJasper** [comment]
Just did a quick test and appears like my suspicion is right, adding the `lazyAnchorRef` fixes this. https://codesandbox.io/s/sandpack-infinite-loading-bug-forked-yhidlp

**Comment by iampava** [comment]
Sounds great! 

Btw, is the sandbox private? I tried opening it now:

![image](https://user-images.githubusercontent.com/11327761/226907752-83c3f093-2750-43bb-b1d0-6d5ee9021d18.png)

**Comment by DeMoorJasper** [comment]
Interesting seems like the default changed to private sometime, should be public now

**Comment by DeMoorJasper** [comment]
> Offtopic: is there a way to easily run these components, for development I mean. I saw the Storybook, it's really helpful but since Storybook adds an iframe around the component I couldn't replicate the bug. So what I ended up doing was to use the components in the landing package, but their code doesn't update if I modify the react package, so I have to rebuild it again and again to test with my modifications.

For this we also use storybook, if you open the story in a new tab it removes the wrapping iframe

<img width="173" alt="Screenshot 2023-03-22 at 13 45 49" src="https://user-images.githubusercontent.com/2175521/226908736-0297e419-3695-46b8-b7f7-08c2b9df987a.png">

**Comment by iampava** [comment]
Oh I see, so that ref wasn't initialized... Yes, it's public now, thanks.

Regarding testing in Storybook, sorry I think I got confused last night, regarding the cause. The problem is that in Storybook the bug doesn't replicate. But if I add it in the `website/landing/pages/index.tsx` it does. But I think we can ignore this problem, probably it's caused by the same bug... 🤷‍♂️

**Comment by danilowoz** [comment]
I believe `lazyAnchorRef` shouldn't be strict to the layout component either to the preview component. The whole SandpackProvider relies on this property to work properly and run the sandboxes, and consequently, other components such as `SandpackConsole` or `SandpackTests` depends on it. 

So, what about moving this logic from `SandpackLayout` to `SandpackProvider`? We could add this ref on `SandpackThemeProvider` which renders a div: 
https://github.com/codesandbox/sandpack/blob/b60bd8906db274685be195b23c6371304fb89e4c/sandpack-react/src/contexts/sandpackContext.tsx#L38-L46

@iampava, would you like to give it a try?

**Comment by iampava** [comment]
Yeah, I'd like to give it a try. Probably will find some time on Wednesday. I'll get back here with some questions if I have them :)

**Comment by danilowoz** [comment]
I'm going to close this issue since it has been a while. Feel free to open it again if you think it should be fixed.
