### ISSUE TITLE
Running Sandpack programatically via the runSandpack API provides stale results

### ISSUE THREAD

**Issue by iampava** [codesandbox/sandpack#852]
# Bug report

## Packages affected

-   [ ] sandpack-client
-   [x] sandpack-react

## Description of the problem

I'm trying to run Sandpack programatically. I found the `runSandpack()` API on the `useSandpack` hook, that seems to do the job. However, the results produced inside `<SandpackPreview>` are stale...

### What steps can we take to reproduce the problem?

1. Navigate to the CodeSandbox I created as sample: https://codesandbox.io/s/sandpack-run-stale-value-ooz9gz?file=/src/App.js
2. Click the **Run** button
3. You'll see the following text
<img width="163" alt="image" src="https://user-images.githubusercontent.com/11327761/226599079-bac8e9ad-f1c8-4fe2-8ca2-907611a0387b.png">

4. Update the text from `Hello World` to `Hello World Sandpack`.
5. The text is updated automatically (although the `autorun` flag is false)  - but this is a separate issue
6. Click **Run** again
7. Update the text from `Hello World` to `Hello World Sandpack Codesandbox`.
8. Click **Run** again
9. Expect to see the text `Hello World Sandpack Codesandbox`. Instead the previous value is shown: `Hello World Sandpack`.

https://user-images.githubusercontent.com/11327761/226601103-3abb27e9-567f-4cee-a8ac-67b70dac9968.mov

### Your Environment

| Software                | Name/Version |
| ----------------------- | ------------ |
| Sandpack-client version |2.1.9|
| Sandpack-react version  |2.1.10|
| Browser                 |Firefox, Chrome|
| Operating System        |Mac OS Ventura|

**Comment by DeMoorJasper** [comment]
I think runSandpack is only for the first start of the sandbox, like having a play button and starting everything lazily after the button is pressed.

There is a `restart` on `useSandpackShell` for this instead

**Comment by iampava** [comment]
Are you sure? I forked the sandbox and used the API you suggested, doesn't seem to be doing what I expect: https://codesandbox.io/s/sandpack-run-stale-value-usesandpackshell-5sevnb?file=/src/App.js

To summarize, I'm looking for something that let's me programmatically run the Sandpack code

**Comment by DeMoorJasper** [comment]
Yup sorry, restart is apparently just for the new nodebox sandboxes. `runSandpack` is the corrent api, but seems to be broken as you found out

**Comment by danilowoz** [comment]
@iampava, can you confirm if it has been fixed on the latest [release](https://github.com/codesandbox/sandpack/pull/875)?
