### ISSUE TITLE
<ErrorOverlay> component doesn't have correct type definitions

### ISSUE THREAD

**Issue by iampava** [codesandbox/sandpack#854]
# Bug report

## Packages affected

-   [ ] sandpack-client
-   [x] sandpack-react

## Description of the problem

Looking at the code of the `<ErrorOverlay>` component it seems it can accept a `className` as prop. However, the type definitions suggest otherwise:

<img width="807" alt="image" src="https://user-images.githubusercontent.com/11327761/226861053-5dda6f78-4a02-4e85-bf9d-35b64ffea517.png">

### Your Environment

| Software                | Name/Version |
| ----------------------- | ------------ |
| Sandpack-client version |2.1.10|
| Sandpack-react version  |2.1.10|
| Browser                 |N/A|
| Operating System        |Mac OS Ventura|

**Comment by DeMoorJasper** [comment]
Thanks for reporting this, typings for ErrorOverlay were definitely a bit weird, simplified them a bit and should be working now
