### ISSUE TITLE
useSandpackConsole and useSandpackShellStdout hooks don't respect maxMessageCount option

### ISSUE THREAD

**Issue by SSHari** [codesandbox/sandpack#865]
# Bug report

## Packages affected

-   [ ] sandpack-client
-   [x] sandpack-react

## Description of the problem
Both the `useSandpackConsole` and `useSandpackShellStdout` hooks don't respect the `maxMessageCount` option. The option is passed in the `useEffect` dependency array, but the default `MAX_MESSAGE_COUNT` value is used instead.

## What were you doing when the problem occurred?
I was trying to change the `maxMessageCount` value for the console in a personal project.

### What steps can we take to reproduce the problem?
1. Render the `Editor` and `Console` components
2. Change the `maxMessageCount` value to something small (e.g. 10)
3. Add more than 10 console log statements to the editor
4. Verify that more than 10 messages are stored in the log

### Your Environment

| Software                | Name/Version |
| ----------------------- | ------------ |
| Sandpack-client version |      -        |
| Sandpack-react version  |    2.1.11       |
| Browser                 |      Chrome        |
| Operating System        |      macOS Ventura        |

**Comment by danilowoz** [comment]
Thank you!
