### ISSUE TITLE
SandpackCodeEditor and SandpackConsole work correctly only when SandpackPreview is around

### ISSUE THREAD

**Issue by chaoticpotato** [codesandbox/sandpack#876]
# Bug report

## Packages affected

-   [ ] sandpack-client
-   [x] sandpack-react

## Description of the problem
SandpackCodeEditor and SandpackConsole work correctly only when SandpackPreview is around

### What steps can we take to reproduce the problem?
SandpackCodeEditor does not show the run button and SandpackConsole does not show console message. If SandpackPreview is added everything starts to work as expected.

### Your Environment

| Software                | Name/Version |
| ----------------------- | ------------ |
| Sandpack-client version |              |
| Sandpack-react version  |     2.2.5         |
| Browser                 |        chrome    |
| Operating System        |          macos ventura    |

**Comment by danilowoz** [comment]
You can use the console component in standalone mode, which will make sure to execute the code:

https://codesandbox.io/p/sandbox/wizardly-morning-31wltk?file=%2Fsrc%2FApp.tsx
