### ISSUE TITLE
Static Template 404s on External Scripts and Stylesheets

### ISSUE THREAD

**Issue by zachmerrill** [codesandbox/sandpack#879]
# Bug report

## Packages affected

-   [ ] sandpack-client
-   [x] sandpack-react

## Description of the problem
I am unable to load external `<script src="" />` or `<link href="" />` tags from the body or head of the static template because they return 404.

![jquery-404](https://user-images.githubusercontent.com/6911696/229667632-d4c1c9d4-eba8-4b6b-9f12-0629a8ccd29c.png)

### What steps can we take to reproduce the problem?

Copy this Sandpack component. It is a static template and attempts to import Bootstrap in a link stylesheet and JQuery in a script.
```tsx
    <Sandpack
      template="static"
      files={{
        "index.html": `<!DOCTYPE html>
  <html lang="en">
    <head>
      <meta charset="UTF-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <meta http-equiv="X-UA-Compatible" content="ie=edge" />
      <title>Static Template</title>
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    </head>
    <body>
      <h1>
        Imports fail to load.
      </h1>
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js"></script>
    </body>
  </html>`
      }}
    />
```

### Your Environment

| Software                | Name/Version |
| ----------------------- | ------------ |
| Sandpack-client version |       2.2.9       |
| Sandpack-react version  |       2.2.9       |
| Browser                 |     Chrome Version 111.0.5563.146 (Official Build) (arm64)         |
| Operating System        |       Mac OS Ventura       |

**Comment by DeMoorJasper** [comment]
Seems we forgot to add a bypass for external ressources in the service worker that powers the static template, fixed in the following commit: https://github.com/codesandbox/static-browser-server/commit/81b52190c8501183970fd8677decae89d43d776e will check after lunch if deploy finished and close if you example works
