### ISSUE TITLE
Update editor code using `updateCode` from `useActiveCode` on page mount

### ISSUE THREAD

**Issue by HichamELBSI** [codesandbox/sandpack#885]
# Bug report

## Packages affected

-   [ ] sandpack-client
-   [x] sandpack-react

## Description of the problem

When I try to update the editor code using the `updateCode` function of the `useActiveCode` hook on component mount, the editor doesn't update. I'm new to this library and I'm sure that this can be done in a cleaner way.

## What were you doing when the problem occurred?

Trying to decode a url search param in order to update the editor code on page mount.

### What steps can we take to reproduce the problem?

The code sandbox is available to try that issue. I don't know if this example is very relevant or if it's the right way to do it but it's pretty much what I'd like to do on my current project. I would like to keep the use of `sandpack-react` components while updating the code on page mount. 

```tsx
// Component to render
import { SandpackProvider } from "@codesandbox/sandpack-react";
import { CustomSandpackLayout } from "./CustomSandpackLayout";

export const App = () => {
  return (
    <SandpackProvider
      theme="auto"
      options={{
        activeFile: "/App.js",
      }}
      files={{
        "/App.js": `export default function App() {
    return (
        <div>Default code</div>
    );
}`,
      }}
      template="react"
    >
      <CustomSandpackLayout />
    </SandpackProvider>
  );
};
```

```tsx
// CustomSandPackLayout.tsx
import {
  SandpackLayout,
  SandpackPreview,
  SandpackCodeEditor,
  useActiveCode,
} from "@codesandbox/sandpack-react";
import { decode, encode } from "../Home/utils";
import { useEffect } from "react";

export const CustomSandpackLayout = () => {
  const { code, updateCode } = useActiveCode();

  useEffect(() => {
    // After the first render, the editor won't update
    updateCode('updated code');

  // For testing purpose, I've tried to add the `updateCode` function to the dependency array, this time, the code is updated but an infinite loop is triggered (obviously).
  }, []);

  console.log(code); // The `code` is never updated

  return (
    <SandpackLayout>
      <SandpackCodeEditor
        initMode="lazy"
        showLineNumbers
        showTabs={false}
        style={{
          height: "100vh",
        }}
      />
      <SandpackPreview
        style={{
          height: "100vh",
        }}
        showNavigator={false}
      />
    </SandpackLayout>
  );
};
```

### Your Environment

| Software                | Name/Version |
| ----------------------- | ------------ |
| Sandpack-client version | x |
| Sandpack-react version  | ^2.2.5 |
| Browser                 | Chrome Version 111.0 |
| Operating System        | macOS Ventura 13.2.1 |

**Comment by danilowoz** [comment]
I can confirm this bug. Apparently, this useEffect is executed after the custom component mount:
https://github.com/codesandbox/sandpack/blob/b1ee2f7a1cb74ca2730877df62b84364494c2295/sandpack-react/src/contexts/utils/useFiles.ts#L59-L61

**Comment by danilowoz** [comment]
In this case, I think you can update the original files props instead of programmatically updating the active file, for example:

```jsx
const [files, setFiles] = useState({})

useEffect(() => {
	const jsxParam = searchParams.get("jsx");
	const decodedJsx = decode(jsxParam);

	setFiles({ "App.js: decodedJsx })
}, [])

<Sandpack files={files} />
```

This should work.

**Comment by HichamELBSI** [comment]
Awesome thank you @danilowoz ! That's exactly what I was looking for 😄
