### ISSUE TITLE
Add Emmet support for code editor

### ISSUE THREAD

**Issue by BeatlesBOB** [codesandbox/sandpack#914]
## Packages affected

-   [ ] sandpack-client
-   [x] sandpack-react

## What is this feature?
As an integrated IDE, it would be very convenient to have the possibility to use Emmet abbreviations. It makes the coding experience much more pleasant

**Comment by danilowoz** [comment]
It can be implemented using an external extension from Codemirror:
- How to use an extension in SandpackCodeEditor: https://sandpack.codesandbox.io/docs/advanced-usage/components#extensions
- Codemirror extension: https://github.com/emmetio/codemirror-plugin
