### ISSUE TITLE
Html head values are ignored

### ISSUE THREAD

**Issue by s4847043** [codesandbox/sandpack#919]
Html document head informations are completely ignored.
<img width="1211" alt="image" src="https://user-images.githubusercontent.com/90407083/234771429-5208c66f-5934-4de4-989f-d3ad6aa12000.png">
I also wrote a test to check if styles work on jest. It works on jest but it is not put in to the generated remote file.
Also title does not change. as you see on the screenshot above.
test below and it is passing:
<img width="716" alt="image" src="https://user-images.githubusercontent.com/90407083/234771881-d59abdf7-783b-4b56-ba8f-64c9c19e38eb.png">

**Comment by SSHari** [comment]
@s4847043 I'm not 100% sure, but the use case that you're describing might be the same as what's mentioned in this issue: https://github.com/codesandbox/sandpack/issues/32. If that's the case then it might not be possible with the template you're using.
