### ISSUE TITLE
Sandpack initialization is a bit slow

### ISSUE THREAD

**Issue by xiaohehennuli** [codesandbox/sandpack#921]
## Sandpack initialization is a bit slow
SandPack initialization is a bit slow. It's likely due to slow installation of dependencies with npm. I have the required dependency packages on my local machine. How can I make SandPack load these local dependencies instead of relying on npm?

## Packages affected

-   [ ] sandpack-client
-   [✅ ] sandpack-react

## Description of the problem
I have the packaged output of @para-ui on my local machine.
![image](https://user-images.githubusercontent.com/48360574/235113158-5e8f16df-9efb-4f4b-b0b6-4b54eb395c4f.png)
Below is my code
![image](https://user-images.githubusercontent.com/48360574/235112442-5e49ef84-6060-46a8-91b9-5ac0940e262b.png)
![image](https://user-images.githubusercontent.com/48360574/235112581-58461d55-46bb-41a6-a0cf-3bd776e432ac.png)

### Your Environment

| Software                | Name/Version |
| ----------------------- | ------------ |
| Sandpack-client version |              |
| Sandpack-react version  |       1.19.0       |
| Browser                 |         chrome     |
| Operating System        |         mac     |

**Comment by danilowoz** [comment]
Hey, indeed the whole process of using an external dependency might be a bottleneck in your project sometimes. Sandpack usually needs to: request, download, parse, transpile, and evaluate each dependency, so you can imagine that it is a lot to the browser. Alternatively, you can try to pass your local packages to the Sandpack context using this [guide](https://sandpack.codesandbox.io/docs/guides/local-dependencies). 

Hope it works for you
