### ISSUE TITLE
Body attributes being stripped

### ISSUE THREAD

**Issue by sufigaffar** [codesandbox/sandpack#924]
# Bug report

## Packages affected

-   [ ] sandpack-client
-   [x] sandpack-react

## Description of the problem

Seemingly, for non-static Sandpack templates, attributes from the body tag are getting stripped. This includes inline styles, which is causing issues for us in some situations. 

## What were you doing when the problem occurred?

Had been comparing the rendered output between a code editor built with Sandpack and CodeMirror, and noticed there were some discrepancies.

### What steps can we take to reproduce the problem?

Using non-static Sandpack template, add a body tag with an inline style and see that it gets stripped from the rendered output. Then try with the static template, and see it works as expected.

### Your Environment

| Software                | Name/Version |
| ----------------------- | ------------ |
| Sandpack-client version |        1.20.9      |
| Sandpack-react version  |       1.20.9       |
| Browser                 |       Arc       |
| Operating System        |       mac OS       |

**Comment by danilowoz** [comment]
It's a hard limitation for runtime sandboxes, see more on https://github.com/codesandbox/sandpack/issues/32
