### ISSUE TITLE
Modified The Themes Builder Website!

### ISSUE THREAD

**Issue by q1b** [codesandbox/sandpack#925]
# Tell us how you think we can improve Sandpack

## Packages affected

-   [ ] sandpack-client
-   [ ] sandpack-react
-   [X] sandpack-theme-website

## What is this feature?

Before the color picker was slow, don’t know why it was using `react-color`, library for providing that, then jumping into the Codebase was my initial impression was, then realised that Maybe recreating it would be much nicer since, I was also looking for some project to work upon!

Here, is link to [GitHub Repo](https://github.com/q1b/sandpack-theme-modified) where code is hosted, All code is done on `iPad Pro M2` with `CodeSandbox Pro Account` really graceful coding experience.

## Do you have any examples of how you would like to see us implement it?
Also, website is hosted on **netlify**, link to website is __*[sandpack-theme-website-link](https://6451576e4894af3253787948--dynamic-sherbet-84b775.netlify.app/)*__

**Comment by danilowoz** [comment]
Close in favor of https://github.com/codesandbox/sandpack/pull/926
