### ISSUE TITLE
Preview displaying incorrect files

### ISSUE THREAD

**Issue by CTNicholas** [codesandbox/sandpack#939]
# Bug report

## Packages affected

-   [ ] sandpack-client
-   [x] sandpack-react

## Description of the problem

The preview doesn't always display the correct files after the `SandpackProvider` `files` prop has been updated.

## What were you doing when the problem occurred?

Updating the `files` prop dynamically.

### What steps can we take to reproduce the problem?

Open [this sandbox](https://codesandbox.io/s/sandpack-bug-preview-not-matching-code-soskc9?file=/src/App.tsx) and look at the default state. The preview shows "Initial", where it should be showing "Updated". You can see the correct active file being logged from `useSandpack().sandpack.files`:

![chrome_2Riutg3Nat](https://github.com/codesandbox/sandpack/assets/33033422/ebe1318f-0beb-430a-b37d-8eaba53db384)

### Your Environment

| Software                | Name/Version |
| ----------------------- | ------------ |
| Sandpack-client version |              |
| Sandpack-react version  | 2.6.4        |
| Browser                 | Chrome & Firefox             |
| Operating System        | Windows 10             |

**Comment by danilowoz** [comment]
Hey, @CTNicholas. It seems it's working for me.

https://github.com/codesandbox/sandpack/assets/4838076/9ef8bc36-7408-433b-86e4-6ee315dfadcd

I noted that you didn't add the SandpackLayout component, which contains an intersection observer to trigger the bundler to start. If this is a limitation for you, so you could:
- Set `sandpack.lazyAnchorRef` on the closest div after `SandpackProvider`, [example](https://github.com/codesandbox/sandpack/blob/dbe036498abeb22e06d8f0ecbe5999089f2e381a/sandpack-react/src/components/common/Layout.tsx#L64);
- Set an option to Sandpack immediately start the bundler `<Sandapck options={{ initMode: "immediate" }} />`

Hope it works for you

**Comment by CTNicholas** [comment]
Thanks for the response @danilowoz ❤! Your suggestion solves the issue in my demo. 

However this fix isn't helping in my real project. I think I've over-simplified the problem in the reproduction—my bad! I'll create a new issue with a better repro next week if I still can't get it working.

Have a nice weekend!
