### ISSUE TITLE
Wrong latest NPM package version

### ISSUE THREAD

**Issue by liorMar** [codesandbox/sandpack#941]
# Bug report

## Packages affected

-   [+] sandpack-client
-   [+] sandpack-react

## Description of the problem

when i request to add a dependency `"@wix/redirects": "latest"`
i get latest version of `1.0.14` while the latest version is `1.0.15` in [NPM](https://www.npmjs.com/package/@wix/redirects) 

## What were you doing when the problem occurred?
playing with a sandbox and trying Sandpack
### What steps can we take to reproduce the problem?

play with a sandbox and create a Sandpack with `"@wix/redirects": "latest"` dependency

### Your Environment

| Software                | Name/Version |
| ----------------------- | ------------ |
| Sandpack-client version |              |
| Sandpack-react version  |              |
| Browser                 |   Chrome           |
| Operating System        |     Mac OS  Monteret 12.6 Intel Core        |

**Comment by danilowoz** [comment]
Hey, @liorMar. Thanks for reporting this issue.

Delays on the dependencies version are expected, as it takes a while to index all the latest versions. I just tested and it seems it's getting the correct one now.

<img width="387" alt="Screenshot 2023-05-19 at 15 23 23" src="https://github.com/codesandbox/sandpack/assets/4838076/0bcc413f-e572-44b7-b65e-1b06ecf9a785">

**Comment by liorMar** [comment]
> Hey, @liorMar. Thanks for reporting this issue.
> 
> Delays on the dependencies version are expected, as it takes a while to index all the latest versions. I just tested and it seems it's getting the correct one now.
> 
> <img alt="Screenshot 2023-05-19 at 15 23 23" width="387" src="https://user-images.githubusercontent.com/4838076/239557715-0bcc413f-e572-44b7-b65e-1b06ecf9a785.png">

strange because i still get `@wix/redirects@1�1.0.14�@wix/redirects@latest�1.0.14`

https://sandpack-cdn-v2.codesandbox.io/v2/deps/QHdpeC9yZWRpcmVjdHNAbGF0ZXN0
