### ISSUE TITLE
Documentation: `console-feed`

### ISSUE THREAD

**Issue by prestonbourne** [codesandbox/sandpack#962]
# Summary

I believe the `console-feed` package should be removed from the `package.json`,  and the www [docs](https://sandpack.codesandbox.io/docs/advanced-usage/components#limitation) since the package is [deprecated](https://www.npmjs.com/package/console-feed) 

## What Happened
After pulling down the repo and running `yarn install` I received a 404 error from yarn. 
```
yarn install v1.22.19
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/console-feed/-/console-feed-3.3.0.tgz: Request failed \"404 Not Found\"".
info If you think this is a bug, please open a bug report with the information provided in "/Users/prestonbourne/Desktop/personal/sandpack/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

I fixed this by simply removing `console-feed` from the dependencies in the `sandbox-client/package.json`

**Comment by danilowoz** [comment]
Thank you for reporting this issue, but Sandpack highly depends on this package and we can't remove it now.
