### ISSUE TITLE
Support read-only mode by file

### ISSUE THREAD

**Issue by gdimitropoulos** [codesandbox/sandpack#97]
Is there a way to make a file not writable  but not hide it from the user ? Rignt now i have hidden the files 
```
   <SandpackProvider template="react" customSetup={{
                files: {
                  "/App.js": Appcode,
                  "/App.test.js": {
                    code: testAppCode,
                    hidden: true
                  },
                  "index.js": indexFile,
                  "SetupTest.js": {
                    code: code,
                    hidden: true
                  } 
                },
....
               
  ```

**Comment by danilowoz** [comment]
Hey @gdimitropoulos, as far as I understood you would like to turn a file read-only for the user?
If so, currently we don't support that, but let me know more about yours needs and then we can consider it 

Thanks

**Comment by gdimitropoulos** [comment]
Yes that was my plan  just  read-only view of the  file
