### ISSUE TITLE
File Explorer

### ISSUE THREAD

**Issue by MaxChu23** [codesandbox/sandpack#98]
Hi, huge thanks for this amazing open-source lib!

One question: what would be the best way to implement a file tree (on the left side, as in CSB)? Are there any hidden places in this library / any external ready-for-use libraries / examples that can be used for this purpose?

Thanks!

**Comment by danilowoz** [comment]
Hey @MaxChu23, glad you're joining Sandpack! 

Currently, we don't officially support the FileExplorer component, as this is a working-in-progress feature and we're taking it into account for future releases. 

However, as we already have a basic version of FileExplorer working - but we are still not confident enough to export it - I think there is no problem sharing this for you, so here's CodeSandbox where you can take these components and implement them on your own in your application.

https://codesandbox.io/s/file-explorer-1ffn6?file=/src/App.tsx:547-565

Hope it helps you.
